State tag naming conventions in javadoc
FabricMC/fabric pull request #1034
Opened 2020-08-20 15:37 UTC by Virtuoel

Currently stating `c` as a namespace (chosen based on [existing conventions](https://fabricmc.net/wiki/tutorial:tag_convention#existing_common_tags) from several Fabric mods).

Currently stating plurals for paths (chosen since the majority of vanilla tags use plurals ([over 80%](https://minecraft.gamepedia.com/Tag#List_of_tags))).

2020-08-20 15:40 UTC, haykam821 requested changes

2020-08-20 15:40 UTC, haykam821 commented on fabric-tag-extensions-v0/src/main/java/net/fabricmc/fabric/api/tag/TagRegistry.java
> + * <p>The convention for paths is plural terms, e.g. {@code c:iron_ingots}, following the majority of vanilla's tags, e.g. {@code minecraft:slabs}, {@code minecraft:gold_ores}
```suggestion
 * <p>The convention for paths is to use plural terms, such as {@code c:iron_ingots}, keeping in line with the majority of vanilla tags such as {@code minecraft:slabs} and {@code minecraft:gold_ores}.
```

2020-08-20 15:58 UTC, TheBrokenRail commented
Maybe ``c:ingots/iron`` instead of ``c:iron_ingots`` so you aren't stuck with a giant tags folder.

2020-08-20 15:59 UTC, haykam821 commented
That isn't convention..

2020-08-20 15:59 UTC, TheBrokenRail commented
Isn't this PR literally defining convention, rather than just picking what other mods use?

2020-08-20 16:01 UTC, haykam821 commented
It wouldn't be convention then.

2020-08-20 16:02 UTC, TheBrokenRail commented
Convention can change, especially if there is a single standard.

2020-08-20 16:05 UTC, haykam821 commented
Usually convention changes in response to a new implementation, rather than documentation.

2020-08-20 16:06 UTC, TheBrokenRail commented
Yes, but most implementations will change to what FAPI says

2020-08-20 16:11 UTC, haykam821 commented
Most changes to Fabric API are agreed upon, and `c:ingots/iron` is not.

2020-08-20 16:23 UTC, TheBrokenRail commented
That is why this is a suggestion sin a PR

2020-08-20 16:32 UTC, i509VCB commented
Convention changes would usually go through a RFC. Clearly we have gone for a PR the standard in and hope no one notices

2020-08-20 19:58 UTC, liach commented
I wonder if player and modmuss want to adopt this. If we add this to fabric api it means fabricmc organization officially back this convention.

2020-08-22 20:07 UTC, Virtuoel commented
Modified to be a placeholder that can be updated if/when conventions are decided upon.

2020-08-23 20:56 UTC, shartte commented
Big 👎 from me. Convention namespace is clearly stated on the _official_ Wiki, and it is "c:".

2020-08-23 21:03 UTC, natanfudge commented
> Modified to be a placeholder that can be updated if/when conventions are decided upon.

Well in that case the PR is pointless. What's the problem with saying the convention is `c`? it definitely won't be anything else, since many mods already use `c`.

2020-08-23 21:36 UTC, Virtuoel commented
I'm personally fine with `c:`, as are many mods as can be seen from tag usage among mods, but as liach mentioned, are modmuss, player, i5, other triage members, etc. fine with adopting the community's current tag namespace and path naming conventions (`c:` and plurals) as *the* conventions endorsed by official javadocs?
If so, great! Just tell me and I'll gladly revert the placeholders so we can finally get a convention that's not just on the wiki.

2020-08-24 08:15 UTC, Earthcomputer commented
If you are a modder learning Fabric, what you want is your mod to *work* with other mods, and there is 1 convention that is vastly more common than any other. Would you really give a fuck about what Fabric officially endorses? Javadocs should be *useful*, these Javadocs are not useful at all, they only mislead the reader away from the frankly more important knowledge that `c:` is the most common convention. If you are going to put Javadocs here at all, best say something like:
```
Although not officially endorsed by Fabric, most mods use {@code c:} as the namespace for common things.
```

2020-08-24 11:17 UTC, TheBrokenRail commented
IMO if an standard is endorsed by Fabric, most existing big resource mods (cotton resources, etc) would probably switch to it quickly, considering its just a bunch of renaming. Thus making it the standard new modders would want to learn.

2020-08-26 21:35 UTC, Virtuoel commented
Updated to state the conventions again, now clarifying that the stated conventions are not official.

2020-08-27 08:15 UTC, Earthcomputer approved these changes

2020-08-27 08:20 UTC, Earthcomputer commented
This looks much better. No javadoc was better than the old javadoc.

2020-08-27 17:09 UTC, liach requested changes
Imo we should just provide a link to the wiki's tag guide. That guide can update while the api is known to be really sluggish at updating.

2020-08-28 08:02 UTC, Vaerian commented
Because this PR kind of touches on a greater discourse in the fabric community I think it would be a really good idea to start an RFC about tag naming conventions (as @i509VCB mentioned) and put this PR on hold given there's been a lot of debate surrounding the topic. It seems like everyone has their own opinion on how we should proceed in the future, and so actually giving the community a chance to have an open dialog about the issue might be beneficial. My personal opinion is that the current "c" namespace is kind of outdated, it grew out of necessity and not actual standard, and there's not a good consensus on how things ought to be named within that namespace (going back to the whole discourse on whether it should be c:ingots/iron or c:iron_ingots or c:iron_ingot), so making a PR for fabric to "officially" endorse a system that is ambiguous seems reckless. I feel like what we need is more of a "de jure" standard for how a common namespace ought to work not a "de facto" norm, and the best way to do that would be through a formal RFC.

Personally I think using something like "common" for the common namespace is a lot more intuitive as to what the namespace is actually for than the "c". Using just one letter isn't helpful to new people trying to mod, or people from outside the community trying to make datapacks that work with fabric. I think someone mentioned that outside of fabric "g" is the standard and I literally had to think for a minute about what "g" could stand for. Having a common namespace as just one letter is not intuitive at all. However, that doesn't really matter right now, the point is that this kind of discussion should be happening in a more public and official setting, not a PR that puts the cart before the horse.

2020-08-28 17:39 UTC, liach commented
I've seen a data pack community declaring `global` as the common namespace. Imo whatever it is we should put it on wiki.

2020-09-22 03:25 UTC, franiscoder commented
I don't like "c" is the common namespace but I also think that fabric can and should take this as a way to show fabric mod compatibility isn't that bad. 
This PR is just a javadoc, it's already not officially supporting it but just a blob of important information.

2020-09-22 03:25 UTC, franiscoder reviewed
I don't like "c" is the common namespace but I also think that fabric can and should take this as a way to show fabric mod compatibility isn't that bad. 
This PR is just a javadoc, it's already not officially supporting it but just a blob of important information.

2021-01-24 11:01 UTC, Technici4n commented
I think having it on the official wiki is good enough.
[The wiki page](https://fabricmc.net/wiki/tutorial:tags) contains much more information than we could put in javadoc anyway, especially given that the wiki lists tags already used by other mods.
For example, if you are hesitating between `aluminum` and `aluminium`, you should use `c:aluminum_*` to ensure Tech Reborn compatibility even if you think it should be called `c:aluminium_*`.

2021-01-24 14:17 UTC, liach commented
This pr should really be edited to add something like

```java
/**
 * @see https://fabricmc.net/wiki/tutorial:tags Tags tutorial on the Fabric Wiki
 */
```

2022-04-27 07:44 UTC, Technici4n commented
I think the new convention tags module properly defines the standard now.

2022-04-27 07:44 UTC, closed without merging