Fix for #987
FabricMC/fabric pull request #1046
Opened 2020-08-25 16:24 UTC by grondag

This PR fixes a defect that causes Indigo to track in incorrect light face after a transform is applied.

As part of the fix, it simplifies geometry tracking generally and also deprecates some public non-API methods that are no longer needed or which should have reduced scope.  The intention is these methods should be removed or changed in the 1.17 cycle.

Lastly, it exposes an improved `fromVanilla` method on `MutableQuadView` that is used in the implementation. This version is more compact and offers better encapsulation and consistency.  The existing method is deprecated and should be removed in the 1.17 cycle.

This change has been briefly tested with a [modified fork of AE2](https://github.com/grondag/Applied-Energistics-2/tree/indigo-fix) to confirm it fixes the reported issue, and also with Exotic Blocks and RenderBender which make extensive use of the API.

Before (with modified AE2 fork that removes current hack)
![2020-08-25_09 07 33](https://user-images.githubusercontent.com/6106235/91199439-be548a00-e6b2-11ea-9e95-7c6f089da8d8.png)

After (with same fork)
![2020-08-25_09 09 13](https://user-images.githubusercontent.com/6106235/91199480-cb717900-e6b2-11ea-91bb-27fd8549316b.png)

2020-08-25 17:50 UTC, sfPlayer1 approved these changes

2020-08-25 18:07 UTC, Juuxel requested changes

2020-08-25 18:07 UTC, Juuxel commented on fabric-renderer-indigo/src/main/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/MutableQuadViewImpl.java
> +	/*
```suggestion
	/**
```
Since this is a javadoc comment.

2020-08-25 18:07 UTC, Juuxel commented on fabric-renderer-indigo/src/main/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/MutableQuadViewImpl.java
> +	/*
```suggestion
	/**
```
Same here.

2020-08-25 18:36 UTC, grondag commented on fabric-renderer-indigo/src/main/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/MutableQuadViewImpl.java
> +	/*
Comments was removed entirely

2020-08-25 19:04 UTC, Juuxel requested changes
I think renderer-api-v1 needs a version bump because of the API change. I suppose it's good otherwise, though I know pretty much nothing about rendering internals 😅

2020-08-25 23:33 UTC, grondag commented
I did bump the minor version and believe that is consistent with Semver conventions for additive, non-breaking changes.

2020-08-26 18:21 UTC, Juuxel approved these changes

2020-08-26 22:19 UTC, modmuss50 approved these changes

2020-08-27 16:56 UTC, NeusFear approved these changes

2020-08-29 04:12 UTC, grondag commented
AFAIK nothing more remains to be done with this one.  Merge at will.

2020-09-03 18:50 UTC, merged