conditional recipes
FabricMC/fabric pull request #1075
Opened 2020-09-11 14:50 UTC by shedaniel

Signed-off-by: shedaniel <daniel@shedaniel.me>

2020-09-11 15:42 UTC, haykam821 commented
Why not allow this for all resources?

2020-09-11 15:58 UTC, shedaniel commented
maybe this could turn into something like libcd then? aka using .mcmeta to define conditions

2020-09-11 16:03 UTC, NinjaPhenix commented on fabric-conditional-resource-api-v1/src/main/java/net/fabricmc/fabric/api/conditionalresource/v1/ResourceCondition.java
>  	boolean process(Identifier recipeId, JsonElement element);
resourceId

2020-09-11 16:03 UTC, i509VCB commented
Conditions should be able to be applied on a per directory scale imo. So a condition would for example not load anything in `data/namespace/tags/blocks/conditional`. How you would do that is going to be another question itself

2020-09-11 16:15 UTC, shedaniel commented
We could have a `<file name>.mcmeta` for per file conditions + `.mcmeta` for the whole directory. (the extension doesn't have to be .mcmeta)

2020-09-12 11:13 UTC, shartte commented
As we discussed yesterday, it could be possible to just have these on a per-directory level, but allow them to define pattern-based conditions. We could then cache these on a per-resource-manager level, reducing the time-to-lookup to once per directory. I'd also not make them "recurse" into subdirectories for simplicity.

2020-09-12 11:27 UTC, shedaniel commented
I have decided to cache it in ResourcePack level since you can have "duplicate" files such as with tags, you don't want to accidentally disable the vanilla one.

2020-09-12 11:28 UTC, shedaniel commented
The current solution of using WrappedResourcePack is not ideal, but that saves me from using a lot of redirects, I will continue to see if there are better solutions

2020-09-12 18:54 UTC, haykam821 requested changes
Needs more codec.

2020-09-12 21:29 UTC, shartte commented
Hmm, I am not sure about it, you might actually want to disable the Vanilla one in case of recipes for example.
Would this _not_ allow you to have a conditional resource declaration that i.e. disables a certain vanilla recipe?

2020-09-13 07:32 UTC, shedaniel commented
Nope, this current PR just hides your json or file if the condition is not satisfied, you can only disable resources in the scope of your resource pack.

2020-10-09 04:20 UTC, Vaerian commented
100% in favor of this idea, I'll come back to review it when it's more finalized

2020-11-12 05:29 UTC, Prospector commented
This is a very cool idea, would love to see it implemented.

2021-01-19 20:49 UTC, i509VCB commented
Superseded by #1264

2021-01-19 20:49 UTC, i509VCB commented
Sorry wrong PR :stuck_out_tongue:

2021-03-13 23:51 UTC, modmuss50 commented
Looks like a resonable start, will need to make sure that it doesnt have an impact on performace too much. I like the idea of applying this to whole folders 👍

2021-03-14 19:12 UTC, liach commented
A resource's condition should be determined at the time a game instance is ready but there is no client or server that would need any resource pack yet (i.e. the blocks, items, etc. are determined, but no resource pack is). Your approach currently determines it in the resource manager, which is inefficient. 

Just a side ref: https://github.com/FabricMC/fabric/pull/1371#issuecomment-798950347.

I hope this can become part of #1373, an improved resource api. Imo this should just become part of the renovated resource api/resource helper than stay in a separate module. If we use these conditions to define custom rules for building the builtin resource pack provided by fabric mods, it would be extremely helpful!

2021-03-27 22:42 UTC, Technici4n commented
Superseded by #1395.

2021-03-27 22:42 UTC, closed without merging