Added client side block place and break events
FabricMC/fabric pull request #1078
Opened 2020-09-12 16:06 UTC by hollandjake

Raised from https://github.com/FabricMC/fabric/pull/1069#issuecomment-690337405

This is a collection of client side events which client side mods can use to detect block breaks and placements.

The added events are as follows:

ClientBlockPlaceEvent.BEFORE
ClientBlockPlaceEvent.CANCELED
ClientBlockPlaceEvent.AFTER

ClientBlockBreakEvent.ON_START
ClientBlockBreakEvent.ON_PROGRESS
ClientBlockBreakEvent.ON_CANCEL
ClientBlockBreakEvent.ON_BREAK

2020-09-21 22:36 UTC, Geometrically requested changes
To be honest, I would just add this to the main BlockPlace/BlockBreak events. Then the event subscriber can do a world.isClient check to see whether they are on the server/client. It's a lot more cleaner, and less messier

2020-09-22 11:02 UTC, hollandjake commented
> To be honest, I would just add this to the main BlockPlace/BlockBreak events. Then the event subscriber can do a world.isClient check to see whether they are on the server/client. It's a lot more cleaner, and less messier

The problem with that is that if the client side mod wants to cancel the removal/placing of a block the serverside event wont be able to do this, as the packet has already been sent to the server. 

Another option is to use the same event but have two points which invoke it. this would create an abstraction for the modders, but under the hood it would be functionally the same as having both

2020-10-19 19:32 UTC, i509VCB requested changes

2020-10-19 19:32 UTC, i509VCB commented on fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/client/player/ClientBlockBreakEvent.java
> +public final class ClientBlockBreakEvent {
Mark the class as client only `@Environment(EnvType.CLIENT)`

2020-10-19 19:32 UTC, i509VCB commented on fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/client/player/ClientBlockPlaceEvent.java
> +	public static final Event<Before> BEFORE = EventFactory.createArrayBacked(
Similarly to my review on server events, the Before phase needs to have cancelation logic split out to an Allow phase

2020-10-19 19:32 UTC, i509VCB commented on fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/MixinClientPlayerInteractionManager.java
> +	private BlockState blockBreakingState;
Mark field as `@Unique`

2020-10-19 19:32 UTC, i509VCB commented on fabric-events-interaction-v0/src/testmod/java/net/fabricmc/fabric/test/event/interaction/ClientBlockBreakEvents.java
> +public class ClientBlockBreakEvents implements ModInitializer {
Entrypoint class name should have test in the name. I thought this was more events at first.

2020-10-19 19:32 UTC, i509VCB commented on fabric-events-interaction-v0/src/testmod/java/net/fabricmc/fabric/test/event/interaction/ClientBlockPlaceEvents.java
> +public class ClientBlockPlaceEvents implements ModInitializer {
Same as other test entrypoint

2020-10-19 19:32 UTC, i509VCB commented on fabric-events-interaction-v0/src/testmod/java/net/fabricmc/fabric/test/event/interaction/ClientBlockPlaceEvents.java
> +public class ClientBlockPlaceEvents implements ModInitializer {
Should be a client initializer.

2020-10-19 19:32 UTC, i509VCB commented on fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/client/player/ClientBlockPlaceEvent.java
> +	 * <p>Called on both client and server. May be used on logical server to send packets to revert client-side block changes.
Client event called on both logical sides?

2020-10-19 19:32 UTC, i509VCB commented on fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/client/player/ClientBlockPlaceEvent.java
> +		boolean beforeBlockPlace(World world, PlayerEntity player, BlockPos pos, BlockState state);
Can specify ClientWorld and ClientPlayerEntity as the parameter types.

2020-11-06 09:31 UTC, oliviathevampire commented on fabric-events-interaction-v0/src/testmod/resources/fabric.mod.json
> +      "net.fabricmc.fabric.test.event.interaction.ClientBlockPlaceEvents",
Should be im "client" since they should be client-side and not on both sides

2020-11-06 09:34 UTC, oliviathevampire commented on fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/MixinClientPlayerInteractionManager.java
> +	public abstract void cancelBlockBreaking();
This does not seem to be used? If it's not used, then it should be removed

2020-11-06 09:35 UTC, oliviathevampire commented on fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/MixinClientPlayerInteractionManager.java
> +	public abstract void cancelBlockBreaking();
This does not seem to be used? If it's not used, then it should be removed

2021-01-19 20:50 UTC, i509VCB commented
Superseded by #1264

2021-01-19 20:50 UTC, closed without merging