Add readme for fabric-lifecycle-events-v1
FabricMC/fabric pull request #1119
Opened 2020-10-12 18:39 UTC by i509VCB

This adds a readme to the module which details all the events the module contains + some details about the events.

2020-10-12 18:41 UTC, Juuxel requested changes

2020-10-12 18:41 UTC, Juuxel commented on fabric-lifecycle-events-v1/README.md
> +The implementation of event callbacks are sub classes.
```suggestion
The implementation of event callbacks are nested classes.
```

2020-10-12 19:35 UTC, OroArmor commented
I like it, but I feel like the dropdown is just a little confusing and could be done differently. I see why it's done this way, but fully expanded, or something like a table, might be easier to find what you need.

2020-10-12 19:36 UTC, i509VCB commented
I definitely want to see a nicer way to organize all of the module in the readme, however other methods feel cluttered. Though the dropdown can feel cluttered after opening up one or two sections

2020-10-12 20:47 UTC, haykam821 requested changes
The mix of Markdown and HTML is unconventional so I'd recommend stripping away the `<details>` and `<summary>` tags, even though it's still valid.

It's better to have two newlines between a header and content as well. In addition, it seems like the headers skip from level 2 to level 4.

There is also a slight inconsistency with natural language ('server world') versus class names (`ServerWorld`). Perhaps we should standardize on one or the other, or even one only at the start of a section?

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerLifecycleEvents.END_DATA_PACK_RELOAD`
```suggestion
#### `ServerLifecycleEvents.END_DATA_PACK_RELOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerLifecycleEvents.START_DATA_PACK_RELOAD`
```suggestion
#### `ServerLifecycleEvents.START_DATA_PACK_RELOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +- In vanilla, this is typically called after `/reload` command is executed.
```suggestion
- In vanilla, this is typically called after the `/reload` command is executed.
```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +- Per the `EndDataPackReload` interface, the last `boolean` parameter specifies whether the data pack reload was successful.
Is `boolean` the actual parameter name? If not, it should either not be formatted or use the actual parameter name.

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +```
````suggestion
```

````

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerTickEvents.START_SERVER_TICK`
```suggestion
#### `ServerTickEvents.START_SERVER_TICK`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerTickEvents.END_SERVER_TICK`
```suggestion
#### `ServerTickEvents.END_SERVER_TICK`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerTickEvents.START_WORLD_TICK`
```suggestion
#### `ServerTickEvents.START_WORLD_TICK`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerTickEvents.END_WORLD_TICK`
```suggestion
#### `ServerTickEvents.END_WORLD_TICK`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerWorldEvents.LOAD`
```suggestion
#### `ServerWorldEvents.LOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerWorldEvents.UNLOAD`
```suggestion
#### `ServerWorldEvents.UNLOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerChunkEvents.CHUNK_LOAD`
```suggestion
#### `ServerChunkEvents.CHUNK_LOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerEntityEvents.ENTITY_LOAD`
```suggestion
#### `ServerEntityEvents.ENTITY_LOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerChunkEvents.CHUNK_UNLOAD`
```suggestion
#### `ServerChunkEvents.CHUNK_UNLOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientBlockEntityEvents.BLOCK_ENTITY_LOAD`
```suggestion
#### `ClientBlockEntityEvents.BLOCK_ENTITY_LOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientBlockEntityEvents.BLOCK_ENTITY_LOAD`
```suggestion
#### `ClientBlockEntityEvents.BLOCK_ENTITY_LOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientEntityEvents.ENTITY_UNLOAD`
```suggestion
#### `ClientEntityEvents.ENTITY_UNLOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientEntityEvents.ENTITY_LOAD`
```suggestion
#### `ClientEntityEvents.ENTITY_LOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientChunkEvents.CHUNK_UNLOAD`
```suggestion
#### `ClientChunkEvents.CHUNK_UNLOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientChunkEvents.CHUNK_LOAD`
```suggestion
#### `ClientChunkEvents.CHUNK_LOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientTickEvents.END_WORLD_TICK`
```suggestion
#### `ClientTickEvents.END_WORLD_TICK`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientTickEvents.START_WORLD_TICK`
```suggestion
#### `ClientTickEvents.START_WORLD_TICK`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientTickEvents.END_CLIENT_TICK`
```suggestion
#### `ClientTickEvents.END_CLIENT_TICK`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientTickEvents.START_CLIENT_TICK`
```suggestion
#### `ClientTickEvents.START_CLIENT_TICK`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientLifecycleEvents.CLIENT_STOPPING`
```suggestion
#### `ClientLifecycleEvents.CLIENT_STOPPING`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ClientLifecycleEvents.CLIENT_STARTED`
```suggestion
#### `ClientLifecycleEvents.CLIENT_STARTED`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerBlockEntityEvents.BLOCK_ENTITY_UNLOAD`
```suggestion
#### `ServerBlockEntityEvents.BLOCK_ENTITY_UNLOAD`

```

2020-10-12 20:47 UTC, haykam821 commented on fabric-lifecycle-events-v1/README.md
> +#### `ServerBlockEntityEvents.BLOCK_ENTITY_LOAD`
```suggestion
#### `ServerBlockEntityEvents.BLOCK_ENTITY_LOAD`

```

2020-10-12 20:56 UTC, Technici4n commented
I think there should be a summary at the top of the README, or maybe on a wiki page listing the various modules? It would be nice to know roughly what each module does without needing to open source files I think.

2020-11-23 08:39 UTC, i509VCB commented
I decided to take a different approach for this module. Since this module is rather wide in scope, I have decided to only document the categories, class names and then write a short sentence explaining what each of the classes contains. I believe the further depth could probably be on wiki or the javadoc should be consulted.

2020-11-26 21:22 UTC, Juuxel requested changes

2020-11-26 21:22 UTC, Juuxel commented on fabric-lifecycle-events-v1/README.md
> +Contains events which indicate the when the lifecycle of a Minecraft Client, Minecraft Server and objects which exist on the client and server have changed.
```suggestion
Contains events which indicate the when the lifecycle of a Minecraft client, Minecraft server and objects which exist on the client and server have changed.
```

2020-11-26 21:22 UTC, Juuxel commented on fabric-lifecycle-events-v1/README.md
> +Contains lifecycle events related to a Minecraft Server.
```suggestion
Contains lifecycle events related to a Minecraft server.
```

2020-11-26 21:41 UTC, Technici4n approved these changes

2020-11-26 21:41 UTC, Technici4n commented on fabric-lifecycle-events-v1/README.md
> +Contains events which indicate the when the lifecycle of a Minecraft client, Minecraft server and objects which exist on the client and server have changed.
the when the?

2020-11-26 21:41 UTC, Technici4n commented on fabric-lifecycle-events-v1/README.md
> +Contains events which indicate the when the lifecycle of a Minecraft client, Minecraft server and objects which exist on the client and server have changed.
either the lifecycle has changed, or the lifecycles have changed (I think)

2020-11-26 21:41 UTC, Technici4n commented on fabric-lifecycle-events-v1/README.md
> +This includes events which indicate a when a server is starting up, is in a data pack reload or shutting down.
a when a

2020-11-28 09:53 UTC, Juuxel approved these changes

2020-11-28 10:39 UTC, YanisBft approved these changes

2020-12-05 11:49 UTC, modmuss50 approved these changes

2020-12-05 19:04 UTC, merged