Add contact links to issue template page
FabricMC/fabric pull request #1244
Opened 2020-12-25 06:38 UTC by i509VCB

This should help direct people who are asking for help to the discord or GitHub Discussions if it is not directly related to issues with or feature requests for Fabric API.

Screenshot:
![image](https://user-images.githubusercontent.com/30619168/103123242-4b035a80-4649-11eb-87af-7b13fe681c2a.png)

2020-12-25 07:12 UTC, haykam821 requested changes

2020-12-25 07:12 UTC, haykam821 commented on .github/ISSUE_TEMPLATE/config.yml
> +  - name: Github Discussions
```suggestion
  - name: GitHub Discussions
```

2020-12-25 07:12 UTC, haykam821 commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Please look here for frequently asked questions and questions on how to use Fabric Api.
```suggestion
    about: Please look here for frequently asked questions and questions on how to use Fabric API.
```

2020-12-25 07:12 UTC, haykam821 commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Please ask here for help with installing Fabric
```suggestion
    about: Please ask here for help with installing Fabric.
```

2020-12-25 14:38 UTC, modmuss50 approved these changes

2020-12-25 16:15 UTC, liach approved these changes

2020-12-25 17:29 UTC, haykam821 approved these changes

2020-12-25 19:18 UTC, sfPlayer1 approved these changes

2020-12-27 23:25 UTC, diabolical17 requested changes
You should add the Fabric Wiki (https://fabricmc.net/wiki)

2020-12-30 16:42 UTC, merged

2026-09-24 12:57 UTC, hsynlybasalbady-glitch reviewed
https://fabricmc.net/use/installer