Add provides entry and change modid
FabricMC/fabric pull request #1263
Opened 2021-01-10 18:54 UTC by AMereBagatelle

This PR at the time of writing does two things:
- Changes the mod id to `fabric-api`
- Adds a `provides` entry with `fabric` as a provided mod

2021-01-10 18:55 UTC, i509VCB requested changes

2021-01-10 18:55 UTC, i509VCB commented on src/main/resources/fabric.mod.json
> +  "provides": [
You need to bump loader dep to use this

2021-01-10 18:56 UTC, AMereBagatelle commented on src/main/resources/fabric.mod.json
> +  "provides": [
Done

2021-01-10 18:58 UTC, modmuss50 commented
You actaully need to bump the loader version in the build.gradle. Please also test to make sure it works as you clearly havent done.

2021-01-10 19:11 UTC, AMereBagatelle commented
The game now actually launches :P
Also, I tested with a mod that depends on the `fabric` modid and it works (I can tell by the warning thrown in the log)

2021-01-14 17:16 UTC, florensie approved these changes

2021-01-20 12:30 UTC, LambdAurora approved these changes

2021-01-25 22:45 UTC, altrisi approved these changes

2021-01-26 15:24 UTC, williambl approved these changes

2021-03-13 23:46 UTC, modmuss50 approved these changes
I forgot about this, seems like everyone else did as well. Pending testing this is good to go as far as I can see.

2021-04-28 14:31 UTC, martmists-gh approved these changes

2021-04-28 16:56 UTC, Juuxel approved these changes

2021-06-09 16:07 UTC, martmists-gh commented
@AMereBagatelle I'd recommend resolving conflicts

2021-06-21 23:18 UTC, AMereBagatelle commented
Conflicts resolved

2021-06-21 23:31 UTC, sfPlayer1 commented
I've been playing with the idea to abuse the mod id change to also change module auto-loading behavior. This could work as follows:
- change the modules' load conditions to if-recommended (except for a few that we always want to load, they'd use if-possible or always)
- change the fapi's mod id to fabric-api
- add a jij with id `fabric` and load condition if-needed that recommends all fapi modules
- make loom auto-generate module deps

-> migrating to fabric-api migrates to opt-in module loading, everything keeps working as expected

Whether we want to do this is TBD, but ultimately relevant for whether the change in this PR should be done or not.

2021-07-23 00:03 UTC, ImperatorStorm approved these changes

2021-09-19 17:06 UTC, liach commented
I'm out of the loop and hope modmuss can decide on this.

2022-01-16 14:52 UTC, altrisi commented
> I've been playing with the idea to abuse the mod id change to also change module auto-loading behavior. This could work as follows:
> 
> * change the modules' load conditions to if-recommended (except for a few that we always want to load, they'd use if-possible or always)
> 
> * change the fapi's mod id to fabric-api
> 
> * add a jij with id `fabric` and load condition if-needed that recommends all fapi modules
> 
> * make loom auto-generate module deps
> 
> 
> -> migrating to fabric-api migrates to opt-in module loading, everything keeps working as expected
> 
> Whether we want to do this is TBD, but ultimately relevant for whether the change in this PR should be done or not.

This sounds really interesting, however, how does it affect the id change?

If the dependencies are going to be generated for specific modules (or, at least, there would be dependencies for separate modules and not a single one for the `fabric-api` id, if I understood correctly), new mods that opt in to that system wouldn't depend directly on `fabric-api` (but on the modules), so I can't see the problem with changing it earlier.

Unless you mean that the mod would depend on `fabric-api` and then loader (or some library/loader plugin by the api) would determine the actual dependencies via those generated dependency metadata. That would solve the problem of people not knowing where to find fabric api if the error screen tells them to get a module, something the other method doesn't provide.

2022-01-16 14:58 UTC, sfPlayer1 commented
You are correct, the fabric-api dep was more meant to serve as user guidance. I however have plans to cover this in metadata format extensions instead, so we may be able to get away with a simple rename after all.

2022-01-16 15:30 UTC, arthurbambou approved these changes

2022-08-05 18:12 UTC, modmuss50 commented
Superseded by [2446](https://github.com/FabricMC/fabric/pull/2446) that targets 1.19.

Thanks everyone for the reviews and feedback on this 👍

2022-08-05 18:12 UTC, closed without merging