Conditional recipes - Revived from #1075
FabricMC/fabric pull request #1395
Opened 2021-03-26 23:37 UTC by OroArmor

Pr #1075 has fallen a bit to the wayside. This PR picks up where it left off. 

The changes I have made so far were switching the storage of `ResourceCondition`s to a registry and exposing the default fabric conditions publicly so that they can be used outside of the API.

2021-03-27 12:44 UTC, frqnny commented on fabric-conditional-resource-api-v1/src/main/java/net/fabricmc/fabric/api/conditionalresource/v1/ResourceConditions.java
> +	 * An always true {@link ResourceCondition}.
Are we sure we need an impossible condition and an always condition?

2021-03-27 23:29 UTC, LambdAurora requested changes
I still maintain that conditional stuff should be handled by resource packs (cf built-in resource packs) with possibly a way to hide them from the user if needed to avoid too much pollution.

`WrappedResourcePack` breaks resource loader `ModResourcePack`.

Wrapping any resource pack coming by is terrible because of group resource packs.

And with the current implementation I am very worried about the slow down this will bring to resource loading with the indexation.

2021-03-27 23:35 UTC, Technici4n commented
> I still maintain that conditional stuff should be handled by resource packs (cf built-in resource packs) with possibly a way to hide them from the user if needed to avoid too much pollution.

I believe there is value in having conditional resources in general, this is easier to manage for modders and it can work nicely with datagen, but if this proves too hard or slow we can just resort to per-recipe and per-advancement conditions like Forge has.

2021-03-28 02:01 UTC, liach commented
Imo group resource pack is a bridgegap measure. We need #1373 to prebuild an actual pack from mod configurations (i.e. shipping existing jsons, generate new jsons based on the possible wood type-woodware types, and applying resource conditions), and that imo would solve most of our problems.

2021-04-03 14:50 UTC, liach commented
> `WrappedResourcePack` breaks resource loader `ModResourcePack`.
> 
> [Wrapping any resource pack coming by is terrible because of group resource packs.](https://github.com/FabricMC/fabric/pull/1395#pullrequestreview-622708415)

Unexpectedly, wrapping resource pack is exactly how vanilla handles format 3/4 resource packs on the client. This just proves the incompatibility of group resource pack imo. I think resource pack grouping should be instead done by a custom implementation of resource pack profile that can return a list of resource packs to resource pack managers.

2021-04-03 14:53 UTC, LambdAurora commented
> > `WrappedResourcePack` breaks resource loader `ModResourcePack`.
> > [Wrapping any resource pack coming by is terrible because of group resource packs.](https://github.com/FabricMC/fabric/pull/1395#pullrequestreview-622708415)
> 
> Unexpectedly, wrapping resource pack is exactly how vanilla handles format 3/4 resource packs on the client. This just proves the incompatibility of group resource pack imo. I think resource pack grouping should be instead done by a custom implementation of resource pack profile that can return a list of resource packs to resource pack managers.

What??

That's a bad idea, doing that would be regression!  
It would re-introduce the whole fucked up priority stuff that mod resource packs suffered before group resource packs were added.

2021-04-06 20:41 UTC, OroArmor commented
It might be better if this is included with the new resource loader that @LambdAurora is going to make, as integrating the systems is a must have, and trying to merge them after the fact will just cause issues

2021-04-16 17:10 UTC, closed without merging