Fluid Flow API
FabricMC/fabric pull request #1402
Opened 2021-03-31 05:05 UTC by OroArmor

Adds an event when a fluid flows. Yes i know its in the object builder API, I'm waiting for #1136 to be merged, or if we merge these into one larger fluid api

2021-03-31 16:17 UTC, PepperCode1 commented
Does this API work for specifying interactions by fluid tag instead of block? Also, does it work for fluid blocks that do not extend `FluidBlock`?

2021-03-31 16:19 UTC, OroArmor commented
No, it doesnt work by tag, as each fluid tag should correspond to a block.
Also no, as it hooks directly into the fluid flow method of fluid block. I don't see why someone would make a fluid that doesn't extend fluid block

2021-03-31 16:22 UTC, OroArmor commented
OHH i see what you mean by tag, but with the current implementation, i don't think its easily addible

2021-03-31 16:37 UTC, Juuxel requested changes
Some general comments about this PR:

- The module for this API is wrong, it definitely does not belong in object builders.
- Using a `Map<Pair<Block, Block>, Event<...>>` could be a better solution: you would get event chaining for free as well as a more usual API. (I'd also change `register` to `Event<...> flowInteraction(Block, Block)` to match normal events)

2021-03-31 16:37 UTC, Juuxel commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/event/fluid/FluidFlowEvents.java
> +	public interface FluidFlowInteractionEvent {
Should be named `FluidFlowInteractionCallback` to match other callbacks.

2021-03-31 16:37 UTC, Juuxel commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/FluidBlockMixin.java
> +			FluidFlowEvents.FluidFlowInteractionEvent event = FluidFlowEvents.getEvent(this, world.getBlockState(pos.offset(direction)).getBlock(), direction);
Might be a nice micro-optimisation and code clarification to cache `pos.offset(direction)` in a variable (and the block state too).

2021-03-31 16:37 UTC, Juuxel commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/event/fluid/FluidFlowEvents.java
> +	public static @Nullable FluidFlowInteractionEvent getEvent(Block flowingBlock, Block interactionBlock, Direction interactionDirection) {
This is a bit concerning, IMO this should allow `Event`-like chaining of callbacks.

2021-03-31 16:37 UTC, Juuxel commented on fabric-object-builder-api-v1/src/testmod/java/net/fabricmc/fabric/test/object/builder/FluidFlowEventTests.java
> +		FluidFlowEvents.register(Blocks.WATER, Blocks.BLUE_ICE, new Direction[]{Direction.DOWN}, (blockState, blockState2, blockPos, world) -> {
This should use the parameter names from the functional interface.

2021-03-31 16:40 UTC, OroArmor commented
The reason i didnt use the current event system is that those are array-based, and this cant easily be array based unless i expose all the data, which would require each event to check if there conditions are met. this is simpler in the sense that you specify the interacting fluid and block to make your callback for

2021-03-31 16:41 UTC, Juuxel commented
You can have a map/collection of events matching to each condition, though. That doesn't require any checks in the callbacks.

2021-03-31 16:43 UTC, OroArmor commented
Ooooohh yeah i could

2021-03-31 16:44 UTC, OroArmor commented
> Using a Map<Pair<Block, Block>, Event<...>> could be a better solution:
I cant use a pair for the block/block matching as the Minecraft pair doesn't have an equals method

2021-03-31 17:04 UTC, PepperCode1 commented
Personally, I think this API should be a callback that is not attached to anything else so that the user has maximum control and so that if a mod needs multiple interactions they can be put into the same callback for more efficiency.

2021-03-31 17:06 UTC, Juuxel commented
@OroArmor You *can* use a `Pair` from some other library or just a custom data class for this as it's an impl detail. I'd still prefer having a public API method returning an `Event` for a block+block+direction combination (or a general event like @PepperCode1 suggested), as that matches the style done everywhere else in FAPI.

2021-03-31 17:06 UTC, OroArmor commented
I dont see it hitting multiple callbacks very often, but in the case it does, its a nice to have

2021-03-31 17:06 UTC, OroArmor commented
Also i should make an impl class for this as there are way to many impl details in the API part

2021-04-03 14:48 UTC, liach commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/event/fluid/FluidFlowEvents.java
> +		List<Pair<Direction, Event<FluidFlowInteractionEvent>>> interactionEvents = flowBlockEvents.getOrDefault(interactionBlock, new ArrayList<>());
You need to learn to use `computeIfAbsent`

2021-04-03 14:48 UTC, liach commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/event/fluid/FluidFlowEvents.java
> +			EVENT_MAP.put(flowingBlock, flowBlockEvents);
Had you used computeIfAbsent, you won't need these in the end

2021-04-03 14:48 UTC, liach commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/event/fluid/FluidFlowEvents.java
> +		if (EVENT_MAP.containsKey(flowingBlock)) {
just check if the get result is null. extra contains check offers no real benefits

2021-04-16 17:10 UTC, closed without merging