Create a test mod for the fabric-content-registries-v0 module
FabricMC/fabric pull request #1491
Opened 2021-06-12 15:35 UTC by haykam821

2021-06-12 15:37 UTC, Technici4n approved these changes
LGTM, does it test every feature of the module?

2021-06-12 15:39 UTC, Juuxel commented
I think testing tag-based fuel values is the only thing that's missing from here.

2021-06-12 15:42 UTC, Technici4n commented
Might be worth adding that, then?

2021-06-12 15:42 UTC, haykam821 commented
It does not test `LootEntryTypeRegistry` which is deprecated in favor of a replacement from another module as well. Testing tags is a good idea, though, and would be beneficial for #1476.

2021-06-13 00:15 UTC, Juuxel approved these changes

2021-06-13 00:20 UTC, liach approved these changes

2021-06-13 00:21 UTC, liach commented
On a side note, I hope we have a place where we look up all the desired behaviors as a result of enabling these test mods than having to look into individual code. Another approach may be to have some unit tests in events, but those would be a bit hard to regulate as well.

2021-06-14 16:15 UTC, modmuss50 requested changes
Would perfer some validation that this has actually worked, crashing the game hard if something isnt quite right would be best.

2021-06-14 16:15 UTC, modmuss50 commented on fabric-content-registries-v0/src/testmod/java/net/fabricmc/fabric/test/registry/ContentRegistryTest.java
> +		FuelRegistry.INSTANCE.add(ItemTags.FOX_FOOD, 20 * 6);
Can we add a check on first tick or something to ensure these have been registered, and crash hard if they havent.

2021-08-02 17:26 UTC, Technici4n commented
@haykam821 Any update?

2022-06-29 10:26 UTC, Technici4n commented
up?

2022-08-31 00:58 UTC, devpelux commented
Doesn't this already exist? In fact there are conflicts...

2022-08-31 08:07 UTC, closed without merging

2022-09-01 00:40 UTC, devpelux commented
Note that Composting and Fuel tests are missing from testmods from all the releases (from 1.17 to 1.19).
All other tests are present.

2022-09-01 09:17 UTC, Technici4n commented
Feel free to open a new PR with proper automated testing then! :)