Replace chunk cache HashSet with HashMap
FabricMC/fabric pull request #1581
Opened 2021-07-18 14:29 UTC by ishland

Fixes https://github.com/FabricMC/fabric/issues/1580

It seems that Minecraft is using a different WorldChunk instance every time. So this uses a HashMap to workaround that issue. 

No memory leak from there after generating ~1493k chunks with [chunky the pregenerator](https://github.com/pop4959/Chunky). (Although I spotted another memory leak from vanilla)

2021-07-18 14:55 UTC, Technici4n commented on fabric-lifecycle-events-v1/src/main/resources/fabric-lifecycle-events-v1.mixins.json
> +    "IWorldChunk",
This mixin is useless.

2021-07-18 14:55 UTC, Technici4n requested changes
I am not sure this changes anything... I can't reproduce the issue in singleplayer at least.

2021-07-18 14:58 UTC, Technici4n commented
Thanks for tackling this. I'm not really sure there is an issue to being with, or maybe I should test on a dedicated server.

2021-07-19 15:27 UTC, ishland commented
Closed as https://github.com/FabricMC/fabric/issues/1580 isn't valid.

2021-07-19 15:27 UTC, closed without merging