Add flattening, stripping and tilling registries
FabricMC/fabric pull request #1632
Opened 2021-08-13 13:20 UTC by Juuxel

Spiritual successor to a small part of #1125 (which I feel should still be resurrected once again, but I'm not the one to do that).

- Adds registries for flattenable blocks (use with shovel), strippable blocks (use with axe) and tillable blocks (use with hoe).
- The registries are close to vanilla, so there is no support for tags (unlike the flammable block registry). If someone needs it, I might look into making them `Block2ObjectMap`s.
- The tillable block registry includes a few extra methods for the most common registration types (block -> block state, block -> block state + drop an item) that use vanilla methods, but also exposes the raw functionality.

2021-08-13 16:36 UTC, Technici4n approved these changes
LGTM, can always be expanded later for custom behavior if necessary.

2021-08-13 16:39 UTC, sfPlayer1 approved these changes
LGTM, thanks! As mentioned on Discord refactoring the module is postponed to a future change.

2021-08-13 16:42 UTC, modmuss50 approved these changes

2021-08-13 21:04 UTC, warjort commented
Maybe HoneycombItem.UNWAXED_TO_WAXED_BLOCKS as well?
But that doesn't look that easy to implement because of the public memoized suppliers.

2021-08-13 21:06 UTC, LambdAurora commented
> Maybe HoneycombItem.UNWAXED_TO_WAXED_BLOCKS as well?
> But that doesn't look that easy to implement because of the public memoized suppliers.

That should be an Oxidized API imo, not really fitting into this.
The issue is it requires asm soup to achieve.

2021-08-13 22:17 UTC, Juuxel commented
@warjort That'd be useful but I feel like it's out of scope since this PR deals with tool interactions. (And if the logic is different, it's probably good to have a separate PR for it anyway)

2021-08-13 23:46 UTC, liach approved these changes

2021-08-13 23:47 UTC, liach commented
> The issue is it requires asm soup to achieve.

@LambdAurora Just curious, do you just mean complex bytecode modification beyond what the current mixin model offers?

2021-08-16 21:03 UTC, Jamalam360 approved these changes

2021-08-17 00:02 UTC, haykam821 requested changes

2021-08-17 00:02 UTC, haykam821 commented on fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/TillableBlockRegistry.java
> +		Objects.requireNonNull(input, "input bock cannot be null");
```suggestion
		Objects.requireNonNull(input, "input block cannot be null");
```

2021-08-17 06:47 UTC, RedGrapefruit09 commented on fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/TillableBlockRegistry.java
> +		Objects.requireNonNull(input, "input bock cannot be null");
**bock**

2021-08-17 06:48 UTC, RedGrapefruit09 approved these changes

2021-08-17 12:55 UTC, haykam821 approved these changes

2021-08-24 16:44 UTC, merged