Update Gradle/Loom and mappings.
FabricMC/fabric pull request #1692
Opened 2021-08-30 12:23 UTC by modmuss50

Gets it up to date on mappings, and makes 1.18 exp snapshots easier.

2021-08-30 12:29 UTC, liach approved these changes

2021-08-30 12:36 UTC, Technici4n approved these changes

2021-08-30 12:50 UTC, NinjaPhenix commented on fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/mixin/content/registry/HoeItemAccessor.java
>  	static Map<Block, Pair<Predicate<ItemUsageContext>, Consumer<ItemUsageContext>>> getTilledBlocks() {
Might aswell rename the accessor as well. Otherwise looks good.

2021-08-30 14:45 UTC, Juuxel requested changes

2021-08-30 14:45 UTC, Juuxel commented on fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/TillableBlockRegistry.java
> +		register(input, usagePredicate, HoeItem.createTillAndDropAction(tilled, droppedItem));
The javadoc of all overloads also references the old HoeItem method names so they have to be renamed as well.

2021-08-31 00:06 UTC, sfPlayer1 approved these changes

2021-08-31 13:00 UTC, merged