Player Tick events
FabricMC/fabric pull request #1787
Opened 2021-10-23 20:53 UTC by AlphaMode

2021-10-24 08:05 UTC, maityyy commented
This will remove a lot of mixins, good idea ;)

2021-10-26 23:33 UTC, Technici4n commented
After discussion on discord, it would be better to add before and after server player tick events. This pair of events could go into the existing `ServerPlayerEvents`.

2021-10-27 06:26 UTC, maityyy commented
> After discussion on discord, it would be better to add before and after server player tick events. This pair of events could go into the existing `ServerPlayerEvents`.

PlayerEntity is only handled from the server? As far as I know, no. **Server**PlayerEvents is very confusing.

2021-10-27 06:30 UTC, Player3324 commented on fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/PlayerEvents.java
> +	public static final Event<BeforePlayerTick> BEFORE_PLAYER_TICK = EventFactory.createArrayBacked(BeforePlayerTick.class, callbacks -> player -> {
<https://github.com/FabricMC/fabric/blob/1.17/fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/api/event/lifecycle/v1/ServerTickEvents.java> introduced START_x_TICK and END_x_TICK as well as a matching theme for the callbacks. Please rename the methods accordingly.

Javadoc also needs to be specific about the the callbacks being invoked on both client and server for all players.

2021-11-17 08:55 UTC, Technici4n commented
@AlphaMode are you planning on updating this PR?

2021-11-23 11:04 UTC, Technici4n requested changes
Naming issues, for consistency with lifecycle and other events. Otherwise LGTM.

2021-11-23 11:04 UTC, Technici4n commented on fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerPlayerEvents.java
> +	public interface BeforePlayerTick {
```suggestion
	public interface StartTick {
```

2021-11-23 11:04 UTC, Technici4n commented on fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerPlayerEvents.java
> +		void prePlayerTick(PlayerEntity player);
```suggestion
		void onStartTick(ServerPlayerEntity player);
```

2021-11-23 11:04 UTC, Technici4n commented on fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerPlayerEvents.java
> +		void prePlayerTick(PlayerEntity player);
Notice the `ServerPlayerEntity`.

2021-11-23 11:04 UTC, Technici4n commented on fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerPlayerEvents.java
> +	public static final Event<BeforePlayerTick> START_PLAYER_TICK = EventFactory.createArrayBacked(BeforePlayerTick.class, callbacks -> player -> {
Should be named `START_TICK`.

2021-11-23 11:04 UTC, Technici4n commented on fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerPlayerEvents.java
> +	public static final Event<AfterPlayerTick> END_PLAYER_TICK = EventFactory.createArrayBacked(AfterPlayerTick.class, callbacks -> player -> {
`END_TICK`

2021-11-23 11:04 UTC, Technici4n commented on fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerPlayerEvents.java
> +	public interface AfterPlayerTick {
```suggestion
	public interface EndTick {
```

2021-11-23 11:04 UTC, Technici4n commented on fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/api/entity/event/v1/ServerPlayerEvents.java
> +		void postPlayerTick(PlayerEntity player);
```suggestion
		void onEndTick(ServerPlayerEntity player);
```

2022-02-10 21:52 UTC, AlphaMode commented
Closed as you can just use the Lookup api with world tick events

2022-02-10 21:52 UTC, closed without merging