Use the correct information when throwing Exceptions for failed tests.
FabricMC/fabric pull request #1927
Opened 2021-12-23 03:34 UTC by jaredlll08

Currently when you fail a GameTest, you don't really get any useful information.
These tests:
```java
    @GameTest(template = "crafttweaker:empty")
    public void alwaysFail(GameTestHelper helper) {
        
        helper.fail("This will always fail because I told it to, this is useful information to know.");
    }

    @GameTest(template = "crafttweaker:empty")
    private void notAccessible(GameTestHelper helper) {
        
        helper.fail("I'm not accessible, since I'm private.");
    }
```

output:
```xml
        <testcase classname="crafttweaker:empty" name="jsonconvertertest.alwaysfail" time="0.082">
            <failure
                    message="Failed to invoke test method (alwaysFail) in (com.blamejared.crafttweaker.gametest.api.data.JsonConverterTest)"/>
        </testcase>
        <testcase classname="crafttweaker:empty" name="jsonconvertertest.notaccessible" time="0.09">
            <failure
                    message="Failed to invoke test method (notAccessible) in (com.blamejared.crafttweaker.gametest.api.data.JsonConverterTest)"/>
        </testcase>
```

Which doesn't really tell me anything about what is wrong with them.

This PR makes it that those tests produce:
```xml
        <testcase classname="crafttweaker:empty" name="jsonconvertertest.alwaysfail" time="0.111">
            <failure message="This will always fail because I told it to, this is useful information to know."/>
        </testcase>
        <testcase classname="crafttweaker:empty" name="jsonconvertertest.notaccessible" time="0.109">
            <failure
                    message="Failed to invoke test method (notAccessible) in (com.blamejared.crafttweaker.gametest.api.data.JsonConverterTest) because class net.fabricmc.fabric.impl.gametest.FabricGameTestHelper cannot access a member of class com.blamejared.crafttweaker.gametest.api.data.JsonConverterTest with modifiers &quot;private&quot;"/>
        </testcase>
```

Which I'm sure we can all agree is way more useful than before.

Something of note, I am *not* using `FabricGameTest` for my test classes.
Looking at the code, I believe if I was I would get the correct information, but as that interface says, it is optional.

2021-12-23 07:07 UTC, deirn approved these changes

2021-12-23 10:16 UTC, Technici4n commented
Looks weird, it seems that the real issue is that the test code doesn't print exception causes? Wouldn't having the full stack trace be even more useful?

2021-12-23 11:38 UTC, Juuxel approved these changes

2021-12-23 11:47 UTC, shartte commented
I also noticed that, yeah. The default reporter isn't all that useful.

2021-12-23 12:50 UTC, shartte commented on fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestHelper.java
> +			throw new RuntimeException(e.getCause().getMessage(), e.getCause());
I actually think if e.getCause() instanceof RuntimeException re, it should throw re directly

At least that's what Vanilla does

2021-12-23 12:53 UTC, shartte requested changes
See my comment about re-throwing e.getCause() in case it's already a runtime exception, like the game test frameworks assertion exceptions are.

2021-12-23 18:50 UTC, jaredlll08 commented
Unless it is a change made by Fabric, I don't believe the Lecturns show the stack trace.

While it is definitely not something I want to address in this PR, I think it may be worthwhile to look into making a new `TestCompletionListener` that does give the stack trace.

What I think the best solution would be would be to let mods define their own `TestCompletionListener` instead of defaulting to the xml based one, I could see someone running their builds on Team City wanting to use the Team City one for example.

2021-12-23 19:37 UTC, liach commented on fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/impl/gametest/FabricGameTestHelper.java
> +			if (e.getCause() instanceof RuntimeException) {
maybe use pattern matching instanceof than call and cast twice

2021-12-23 19:43 UTC, liach approved these changes

2021-12-23 20:14 UTC, Technici4n commented
> Unless it is a change made by Fabric, I don't believe the Lecturns show the stack trace.
> 
> While it is definitely not something I want to address in this PR, I think it may be worthwhile to look into making a new `TestCompletionListener` that does give the stack trace.
> 
> What I think the best solution would be would be to let mods define their own `TestCompletionListener` instead of defaulting to the xml based one, I could see someone running their builds on Team City wanting to use the Team City one for example.

Yes, that would be neat indeed eventually. For now, this PR is already a net improvement.

2021-12-23 20:14 UTC, Technici4n approved these changes

2021-12-23 23:42 UTC, sfPlayer1 approved these changes

2021-12-23 23:48 UTC, modmuss50 approved these changes

2021-12-26 15:07 UTC, liach commented
@modmuss50 should be good to go?

2021-12-26 15:11 UTC, modmuss50 commented
> @modmuss50 should be good to go?

Yes I know.. hence why I added the ready to merge label. I have been busy the last few days so havent gotten the chance to merge it. Its also quite trivial so there is no major rush?

2022-01-02 18:56 UTC, merged