Fix #1947, #1873: FabricBlockSettings#copy does not copy all settings, the sequel
FabricMC/fabric pull request #2119
Opened 2022-04-10 16:28 UTC by Luligabi1

Same as #1984, I changed the branch's name and github automatically closed the previous PR. Sorry about that 😅

2022-04-13 14:03 UTC, deirn approved these changes

2022-04-13 15:08 UTC, Technici4n approved these changes

2022-04-13 21:23 UTC, Juuxel requested changes
See https://github.com/FabricMC/fabric/issues/1873#issuecomment-981202311; I'd add a note here that this copies more than vanilla's `AbstractBlock.Settings.copy` (the change itself is good)

2022-04-14 02:11 UTC, Luligabi1 commented
> See [#1873 (comment)](https://github.com/FabricMC/fabric/issues/1873#issuecomment-981202311); I'd add a note here that this copies more than vanilla's `AbstractBlock.Settings.copy` (the change itself is good)

Added to header javadoc, reply if the note should be altered or moved to other place.

2022-04-14 10:25 UTC, Juuxel approved these changes
I'd personally put the note in the `copyOf` methods but this works too.

2022-04-22 20:00 UTC, modmuss50 approved these changes

2022-05-15 21:40 UTC, Hugman76 approved these changes

2022-05-20 17:17 UTC, merged