Load mod-provided data packs and DRM entries in CreateWorldScreen
FabricMC/fabric pull request #2261
Opened 2022-05-27 15:43 UTC by apple502j

Fixes #2225

There were 2 issues in the existing `CreateWorldScreenMixin` mixin, specifically with `create(MinecraftClient, Screen)` method:

- There were two references to `DataPackSettings#SAFE_MODE`. The first one was used to load the DRM, and the second one is passed to the constructor. Previously, only the second one was replaced to include Fabric-provided data packs.
- There were no attempts to load dynamic registry from the provided data packs.

This fixes both issues, plus a code change to try-with-resources `createResourcePack`.

One way to test this is to use Biome API to register a placed feature from a data pack, which is not included in the testmod (yet). Previously it crashed the game, but it should no longer crash. If anyone can help testing this PR, I'd really appreciate that.

2022-05-28 04:15 UTC, maityyy requested changes

2022-05-28 04:15 UTC, maityyy commented on fabric-resource-loader-v0/src/client/java/net/fabricmc/fabric/mixin/resource/loader/client/CreateWorldScreenMixin.java
> +	@Redirect(method = "method_41854", at = @At(value = "INVOKE", target = "Lnet/minecraft/util/registry/DynamicRegistryManager$Mutable;toImmutable()Lnet/minecraft/util/registry/DynamicRegistryManager$I
Remove `remap = false` to avoid crash outside dev env

2022-05-28 14:52 UTC, apple502j commented
Seems like this still crashes in dedicated/gametest server. Need to fix this.

2022-05-29 21:13 UTC, Juuxel approved these changes

2022-05-30 11:08 UTC, modmuss50 approved these changes
Looks fine, I assume this is 1.19 only?

2022-05-30 11:14 UTC, apple502j commented
The code for dedicated servers need 1.18.2 backport. Client-side code I believe should be fine, but we need some testing. No backport is necessary for 1.18.1 or earlier, as ServerBugfixMixin handles these cases.

2022-05-30 13:00 UTC, maityyy approved these changes

2022-05-31 11:11 UTC, merged