Change client command api to use rgeistration event
FabricMC/fabric pull request #2264
Opened 2022-05-29 05:08 UTC by jpenilla

Allows usage of CommandRegistryAccess in client command arguments more easily

2022-05-29 06:45 UTC, apple502j requested changes

2022-05-29 06:45 UTC, apple502j commented on fabric-command-api-v2/src/client/java/net/fabricmc/fabric/api/client/command/v2/ClientCommandManager.java
> +import javax.annotation.Nullable;
I believe we use the one from jetbrains annotation

2022-05-29 06:45 UTC, apple502j commented on fabric-command-api-v2/src/client/java/net/fabricmc/fabric/impl/command/client/ClientCommandInternals.java
> +import javax.annotation.Nullable;
same here

2022-05-29 06:45 UTC, apple502j commented on fabric-command-api-v2/src/client/java/net/fabricmc/fabric/impl/command/client/ClientCommandInternals.java
> +	private static CommandDispatcher<FabricClientCommandSource> DISPATCHER;
I don’t think we uppercase nonfinal fields

2022-05-29 06:45 UTC, apple502j commented on fabric-command-api-v2/src/client/java/net/fabricmc/fabric/impl/command/client/ClientCommandInternals.java
> +	private static CommandDispatcher<FabricClientCommandSource> DISPATCHER;
also this should be marked as `@Nullable`

2022-05-29 06:45 UTC, apple502j commented on fabric-command-api-v2/src/client/java/net/fabricmc/fabric/impl/command/client/ClientCommandInternals.java
> +	public static void setActiveDispatcher(CommandDispatcher<FabricClientCommandSource> dispatcher) {
This accepts null, right?

2022-05-29 06:45 UTC, apple502j commented on fabric-command-api-v2/src/client/java/net/fabricmc/fabric/api/client/command/v2/ClientCommandManager.java
> +	 * <p>May be null when not connected to a server.</p>
If client commands do work in integrated environment, this is misleading, since you only “connect” to dedicated servers. “not in a world” might work.

2022-05-29 21:11 UTC, sfPlayer1 approved these changes

2022-05-29 21:16 UTC, Juuxel approved these changes
LGTM, this is pretty close to the original design of the client command API before I had to change it to a raw dispatcher 😄

2022-05-29 21:19 UTC, Technici4n approved these changes

2022-05-30 11:04 UTC, modmuss50 approved these changes
Not ideal to have breaking changes, but seems like its the best way forward.

2022-05-30 11:04 UTC, modmuss50 commented
Putting this into last call for a little (not the whole week) as this needs to go in ASAP.

2022-05-30 11:10 UTC, apple502j approved these changes

2022-05-31 11:11 UTC, merged

2022-06-07 13:27 UTC, Earthcomputer commented on fabric-command-api-v2/src/client/java/net/fabricmc/fabric/mixin/command/client/ClientPlayNetworkHandlerMixin.java
> +	@Inject(method = "onGameJoin", at = @At("HEAD"))
This causes race conditions as it occurs on both the netty thread and the main thread

2022-06-07 14:05 UTC, haykam821 commented on fabric-command-api-v2/src/client/java/net/fabricmc/fabric/mixin/command/client/ClientPlayNetworkHandlerMixin.java
> +	@Inject(method = "onGameJoin", at = @At("HEAD"))
By the way, should this initialization be moved to when the server command tree packet is received? That would also allow the command registry access to be shared between server and client commands.