Message API update (wip)
FabricMC/fabric pull request #2296
Opened 2022-06-08 15:19 UTC by apple502j

WIP, untested.

This update will bring three things:

- `ClientMessageEvents`. Like `ServerMessageEvents`, if the message is blocked by the client, it won't be handled. It uses a similar set of callbacks using the same parameter orders with the server-side ones, however command callback obviously does not exist, and `RegistryKey<MessageType> typeKey` is replaced with `MessageType type` due to technical reasons. (Those who need the key can lookup DRM.) Currently there is no Allow callback. This is implemented by adding a custom `ClientChatListener` to `InGameHud#listeners`.
- `ClientMessageHelper`. The event will receive `MessageSender`, but the client might want to resolve the otherwise-empty record; these methods provide UUID-to-entity/player list entry lookup.
- (NOT PUSHED) `ServerChatEvents#MODIFY_SENDER_NAME` event. This can be used for coloring player names (note that custom message type might be better), pronouns mods, nicknames, etc. Since the name is not signed, we can modify this with no issue. This will use event phases like `ServerMessageDecoratorEvent`.

2022-06-09 15:58 UTC, apple502j commented
Note: MODIFY_SENDER_NAME is postponed. This PR is therefore ready to review.

2022-06-26 09:06 UTC, Technici4n commented
So this is not in progress anymore?

2022-06-26 10:30 UTC, apple502j commented
@Technici4n Yes

2022-06-26 10:33 UTC, Technici4n commented
Seems easy enough. What would be the use case? Would the ability to cancel the message and/or change it would make sense compared to only having "notification" callbacks?

2022-06-28 17:41 UTC, apple502j commented
@Technici4n Not sure about the use case for changing the message client-side. Canceling might have a use, but probably later.

Main use case would be mods that ping the user or store messages in other places.

2022-06-28 21:15 UTC, Technici4n commented
Sure thing, I assume cancel and modify would be different events running before the ones added by this PR anyway; they could easily be added after the fact.

2022-06-29 09:22 UTC, Technici4n requested changes
I'm going to request a small testmod. ;)

2022-07-08 19:50 UTC, apple502j commented
Closing; will PR targeting 1.19.1 instead.

2022-07-08 19:50 UTC, closed without merging