Message Channels
FabricMC/fabric pull request #2478
Opened 2022-08-23 02:29 UTC by BlueZeeKing

# Message API Message Channels

## Resolves

Implements some of #1147 

## What is this?

This adds more functionality to the message API by adding message channels. These channels allow mods to control who can see which chat messages. They work by using the `MessageChannels.setChannel` with the UUID of the player and the identifier of the channel. That means the player can only send and receive messages in their channel. To go back to the global channel set the player's channel to `MessageChannels.GLOBAL_CHANNEL`.

## What does this not do?

This API operates only on the server and doesn't modify the actual content on the chat. The channel data is also not persistent across server restarts so any mod using will have to store that data on its own.

## Testing

This mod was tested using the `/fabric-message-api-v1-test set` command that is included in the testmod. It was tested using two Minecraft accounts joining one server. The `/say` and `/me` commands were tested. Global and custom channels were also tested.

2022-08-23 04:12 UTC, haykam821 requested changes
The documentation makes a few grammatical mistakes and does not follow the convention of prefixing `@param` and `@return` descriptions with lowercase letters.

2022-08-23 04:12 UTC, haykam821 commented on fabric-message-api-v1/src/main/java/net/fabricmc/fabric/api/message/v1/MessageChannels.java
> +public class MessageChannels {
```suggestion
public final class MessageChannels {
```

2022-08-23 04:12 UTC, haykam821 commented on fabric-message-api-v1/src/main/java/net/fabricmc/fabric/api/message/v1/MessageChannels.java
> +	private static final HashMap<UUID, Identifier> playerChannels = new HashMap<>();
This field should follow static naming conventions.

2022-08-23 04:17 UTC, apple502j requested changes
I believe message channels are a bit out of scope. Mods can implement it easily now that AllowChatMessage event exists.

That said, if we do provide it, then we should use that event instead of mixin. Also how would message channel work with commands, particularly ones /executed?

2022-08-23 04:27 UTC, apple502j commented
Ah, this is per-player. Then we need a new event, yeah. That said we should provide this as generic event, not usage-specific one.

2022-08-24 16:13 UTC, BlueZeeKing commented
> Ah, this is per-player. Then we need a new event, yeah. That said we should provide this as generic event, not usage-specific one.

I think you're right. I can keep the mixins the same and add the event.

2022-08-31 11:02 UTC, apple502j reviewed
Note to self: this does send header packet, so that's good

2022-09-02 09:29 UTC, apple502j requested changes

2022-09-02 09:29 UTC, apple502j commented on fabric-message-api-v1/src/main/java/net/fabricmc/fabric/api/message/v1/ServerMessageEvents.java
> +	 * <p>This also applies to {@see net.minecraft.server.PlayerManager#broadcast()}
```suggestion
	 * An event triggered when a player sends a chat message. Listeners on this event
	 * are triggered for every player receiving that message. If any listener attached returns
	 * {@code false} the message body will not be sent to that specific player. However,
	 * due to client-side limitations, the header (which includes the sender profile)
	 * will always be sent. Note that this only applies to messages sent by a player,
	 * not other entities (via {@code /execute}).
	 *
	 * <p>If a listener returns {@code false}, the server will not broadcast the message body
	 * to that player and no further listeners will be run.
	 *
	 * <p>This event is triggered after {@link #CHAT_MESSAGE}, {@link #COMMAND_MESSAGE},
	 * or their allow variant. If those events blocked the message body from being sent,
	 * then this event will not be triggered.
```

2022-09-02 09:29 UTC, apple502j commented on fabric-message-api-v1/src/main/java/net/fabricmc/fabric/api/message/v1/ServerMessageEvents.java
> +		 * <p>This only applies to messages sent by a player.w
```suggestion
		 * Called when a player is going to be sent a message either from the chat GUI or a
		 * command (including player specific commands such as {@code /msg}). Returning {@code false}
		 * prevents only this player from receiving the message body. However,
		 * due to client-side limitations, the header (which includes the sender profile)
		 * will always be sent.
		 *
		 * <p>This only applies to messages sent by a player, not other entities (via {@code /execute}).
```

2022-09-02 09:29 UTC, apple502j commented on fabric-message-api-v1/src/main/java/net/fabricmc/fabric/api/message/v1/ServerMessageEvents.java
> +		 * @param sender the uuid of the player that sent the message
```suggestion
		 * @param sender the UUID of the player that sent the message
```

2022-09-02 09:29 UTC, apple502j commented on fabric-message-api-v1/src/main/java/net/fabricmc/fabric/mixin/message/ServerPlayerEntityMixin.java
> +		UUID sender = ((SentMessageChatAccessor) message).getMessage().createMetadata().sender();
```suggestion
		UUID sender = signedMessage.signedHeader().sender();
```

2026-02-23 03:45 UTC, closed without merging