22w42a RegSync changes, add EndDynamicRegistrySetupCallback
FabricMC/fabric pull request #2608
Opened 2022-10-26 03:37 UTC by apple502j

While this is ABI compatible, I'd still like to call this a breaking change because old code certainly crashes. (See javadoc)

`EndDynamicRegistrySetupCallback` can be postponed if we need quicker fix for the bugs.

- Fix `DynamicRegistrySetupCallback` being called too late
- Remove unused code
- Mark impl as internal

2022-10-27 14:05 UTC, Technici4n reviewed
Would be nice to have some tests that validate the changed behavior in case this gets changed again in an upcoming snapshot.

2022-10-27 21:34 UTC, Technici4n requested changes
Looks pretty good. One small clarification request.

2022-10-27 21:34 UTC, Technici4n commented on fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistrySetupCallback.java
> + * contain the registry. Use {@link DynamicRegistryManager#getOptional} to
This is due to the multiple layers, right? In that case, it would be good to explain this somewhere.

2022-10-28 01:05 UTC, apple502j commented on fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/DynamicRegistrySetupCallback.java
> + * contain the registry. Use {@link DynamicRegistryManager#getOptional} to
yep

2022-10-28 09:22 UTC, Technici4n approved these changes
Maybe a link to a class referencing the various layers too?

2022-10-28 17:02 UTC, modmuss50 commented on fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/package-info.java
> +package net.fabricmc.fabric.impl.registry.sync;
Question, I wonder if putting a package-info.java marked with `@ApiStatus.Internal` in api-base in `net.fabricmc.fabric.impl` would cover all the modules? (not something for this PR)

2022-10-28 17:03 UTC, modmuss50 commented on fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/package-info.java
> +package net.fabricmc.fabric.impl.registry.sync;
Oh, I guess it wont popagate to the sub packages (based on the next files in the PR).

2022-10-28 17:04 UTC, modmuss50 approved these changes

2022-10-28 17:24 UTC, merged