Entity Selector Option API
FabricMC/fabric pull request #2667
Opened 2022-11-19 11:49 UTC by apple502j

Adds an entity selector option API.

## FAQ
### Is this a port from (insert another API library)?
No. The underlying design might be similar (after all, this is just a wrapper method), but the code is written entirely by me. This also adds an easy way to make a non-repeatable selector.

### Is this tested?
Yes, actually this is tested using GameTest!

2022-12-28 12:46 UTC, Technici4n requested changes

2022-12-28 12:46 UTC, Technici4n commented on fabric-command-api-v2/src/main/java/net/fabricmc/fabric/api/command/v2/FabricEntitySelectorReader.java
> +		throw new UnsupportedOperationException("Not implemented");
```suggestion
		throw new UnsupportedOperationException("Implemented via mixin");
```

2022-12-28 12:46 UTC, Technici4n commented on fabric-command-api-v2/src/main/java/net/fabricmc/fabric/api/command/v2/FabricEntitySelectorReader.java
> +		throw new UnsupportedOperationException("Not implemented");
```suggestion
		throw new UnsupportedOperationException("Implemented via mixin");
```

2022-12-28 12:46 UTC, Technici4n commented on fabric-command-api-v2/src/main/java/net/fabricmc/fabric/mixin/command/EntitySelectorOptionsAccessor.java
> +	static void callPutOption(String id, EntitySelectorOptions.SelectorHandler handler, Predicate<EntitySelectorReader> condition, Text description) {
Funny how the two classic types of options are called "call options" and "put options" in finance. :smile:

2022-12-28 13:03 UTC, Technici4n approved these changes

2023-01-01 18:56 UTC, deirn commented
I noticed that you can use Identifier as the key, but it needs to be quoted for it to work. Should we do that instead of replacing it with underscores? Might need to hack around the autocomplete suggestion though.

2023-01-02 06:28 UTC, apple502j commented
@deirn I don't think that's very useful.

2023-01-02 14:52 UTC, modmuss50 approved these changes

2023-01-05 12:49 UTC, merged