add c:shields common tag
FabricMC/fabric pull request #2727
Opened 2022-12-05 16:19 UTC by itsmiir

added a `c:shields` tag and added `minecraft:shield` to it. first FAPI pr so let me know if i messed something up 😆

2022-12-05 17:32 UTC, Juuxel requested changes
You need to regenerate the tag files. I think the command for that is `gradlew :fabric-convention-tags-v1:generateResources`

2022-12-05 18:10 UTC, itsmiir commented
i thought i did that-- looks like the tag files were gitignored. is this all that's needed?

2022-12-05 18:17 UTC, Juuxel approved these changes

2022-12-07 18:33 UTC, modmuss50 approved these changes

2022-12-11 13:50 UTC, merged