Autogenerate Item constructor TAWs
FabricMC/fabric pull request #2795
Opened 2022-12-26 07:27 UTC by Shnupbups

`generateAccessWidener` task in TAW module will now automatically generate TAWs for the constructors of non-abstract item classes, similar to how it already did so for blocks. As such, previously manually added item constructor TAWs have been removed from the template. This also means that `HoeItem` is now TAW'd. (I totally overlooked it earlier... whoops!)

2022-12-26 08:17 UTC, Noaaan approved these changes
Nice

2022-12-26 12:54 UTC, Juuxel approved these changes
LGTM. This is already in use with the exact same logic in [Architectury API](https://github.com/architectury/architectury-api/blob/d979caa4ab7bb4980f673f50b9c00aea2349b738/common/build.gradle#L89) (mojmap warning!) too.

2022-12-27 13:35 UTC, Technici4n requested changes
Please also add previously missed TAWs. For example, https://github.com/FabricMC/fabric/blob/1.19.3/fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/api/client/screen/v1/Screens.java should be deprecated and replaced by TAWs. I believe it would be worth going through all the accessor mixins and checking for similar ones.

2022-12-28 08:28 UTC, Shnupbups commented
> Please also add previously missed TAWs. For example, https://github.com/FabricMC/fabric/blob/1.19.3/fabric-screen-api-v1/src/client/java/net/fabricmc/fabric/api/client/screen/v1/Screens.java should be deprecated and replaced by TAWs. I believe it would be worth going through all the accessor mixins and checking for similar ones.

Eh, I'd say that is out of scope for this simple PR and should be a follow up.

2022-12-28 12:07 UTC, Technici4n commented
I think it's reasonable to many missed TAWs in a single pass, see also #2780 where I addressed multiple issues at once.

2022-12-30 17:49 UTC, Noaaan commented
Would adding a TAW for `StatusEffect` also be suitable to do in this pass? This constructor is also protected.

2023-01-02 11:57 UTC, modmuss50 commented on fabric-transitive-access-wideners-v1/build.gradle
> +	Files.list(fs.getPath("net/minecraft/item"))
This is fine for now, in the future it may be better to check the class hierarchy similar to how I did it in the data gen module.

2023-01-02 11:57 UTC, modmuss50 approved these changes

2023-01-02 13:05 UTC, merged