Replace useless nullability comments with jetbrains annotation
FabricMC/fabric pull request #2800
Opened 2022-12-27 06:23 UTC by SilverAndro

This broke my automated tooling which relies on knowing nullability (specifically the block break events fucked it up). I very much hope you aren't planning to add more of these into the codebase because these are tremendously annoying and I assumed it was some "smart view" mode in my IDE hiding the actual annotation.

2022-12-27 06:29 UTC, apple502j commented
Are they all nullable, or in fact not nullable and commented out for reasons?

2022-12-27 06:30 UTC, SilverAndro commented
I know the block ones are nullable at least for sure, since thats what exploded at runtime

2022-12-27 06:38 UTC, SilverAndro commented
Item ones were old comments, I have no clue on the entity builder because theres both a requireNonNull and a "if not null", which seems to imply it can be null but only while building? Theres 0 hints at the intent here
![image](https://user-images.githubusercontent.com/52360088/209622781-3951e49b-1c5b-4e2a-ba89-1b7f26b23c52.png)

2022-12-27 06:47 UTC, SilverAndro commented
Going to assume its supposed to be nullable internally for building, since
- The field is private, meaning its not public API
- The setter requires the passed value to not be null (only place its interactable in public API)
- The build method makes a check if its not null, because it can be null if the public api consumer doesn't call the set method

Since reading isnt exposed anywhere, it doesn't really matter since it has 0 impact on public API

2022-12-27 09:36 UTC, apple502j requested changes
Could you run checkstyle and fix the import sorting issues?

2022-12-27 09:36 UTC, apple502j commented on fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/ItemExtensions.java
> +	EquipmentSlotProvider fabric_getEquipmentSlotProvider();
Now that I think about this, it is probably nullable.

2022-12-27 13:44 UTC, apple502j commented on fabric-item-api-v1/src/main/java/net/fabricmc/fabric/impl/item/FabricItemInternals.java
> +		private EquipmentSlotProvider equipmentSlotProvider;
These too are nullable, I believe this was coded back when nullable annotations were not used?

2022-12-31 08:19 UTC, apple502j approved these changes

2023-01-02 11:54 UTC, modmuss50 approved these changes

2023-01-02 13:04 UTC, merged