Resource Conditions Additions
FabricMC/fabric pull request #2821
Opened 2023-01-03 11:58 UTC by Technici4n

- Add `registry_contains` condition. Closes #2548.
- Make `fabric:load_conditions` appear first in generated JSON objects.
- Uniformize implementation a bit:
  - Move the features enabled `ConditionJsonProvider` implementation up next to the other provider implementations.
  - Rename and finalize `ThreadLocal<FeatureSet> currentFeature` to `final ThreadLocal<FeatureSet> CURRENT_FEATURES`.

2023-01-03 11:59 UTC, Technici4n commented on fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/api/resource/conditions/v1/DefaultResourceConditions.java
>  	}
I know this is ugly, but it makes the vararg manipulation a lot shorter, which makes the behavior of the various factory methods much easier to follow for someone reading through them the first time. Worth it imo. :wink:

2023-01-25 08:57 UTC, modmuss50 approved these changes

2023-02-01 21:32 UTC, Juuxel requested changes

2023-02-01 21:32 UTC, Juuxel commented on fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/mixin/resource/conditions/DataProviderMixin.java
> +	@Dynamic // lambda method passed to Util.make
```suggestion
	@Dynamic("lambda method passed to Util.make")
```

Dynamic can also take the description as a parameter which is used elsewhere in fabric api:
https://github.com/FabricMC/fabric/blob/0780111d1981ebd00ff5c399c2bc8131f866f26e/fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/LivingEntityMixin.java#L99

2023-02-01 21:32 UTC, Juuxel commented on fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/api/resource/conditions/v1/DefaultResourceConditions.java
> +	public static ConditionJsonProvider itemsLoaded(ItemConvertible... items) {
Maybe `itemsRegistered` since it wraps `registry_contains`? I don't think we usually talk about loading items, except item models and such

2023-02-13 09:30 UTC, merged