Apply disabled shade from vanilla quads directly to material
FabricMC/fabric pull request #2898
Opened 2023-02-09 01:19 UTC by PepperCode1

`QuadViewImpl` no longer stores a hidden `shade` boolean that cannot be copied. `MutableQuadViewImpl#fromVanilla` now modifies the passed material to force disable diffuse if the vanilla quad has shade disabled. This leads to the exact same behavior as before these changes, except that the material now accurately represents the diffuse state of the quad.

2023-02-13 15:21 UTC, Technici4n requested changes
Looks very good overall, just a few comments.

2023-02-13 15:21 UTC, Technici4n commented on fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/mesh/MutableQuadViewImpl.java
> +		if (!quad.hasShade()) {
Note to self: When the quad has shade and the material does not, an "opinionated" choice needs to be made on whether to shade or not here. I'm fine with the current behavior of disabling the shade if either the quad or the material disables it.

2023-02-13 15:21 UTC, Technici4n commented on fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/BlockRenderInfo.java
>  	boolean shouldDrawFace(Direction face) {
Mark it as `@Nullable` maybe?

2023-02-13 15:21 UTC, Technici4n commented on fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractQuadRenderer.java
> +			// handle them. Generally only applies to modded models.
Why?

2023-02-13 15:21 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/impl/renderer/RendererHolder.java
> +	/** avoids null test every call to {@link #isPresent()}. */
That's weird, `null` checks should largely be fast enough. But it was already there so /shrug.

2023-02-13 15:21 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/Renderer.java
> +	static Renderer get() {
Could we maybe have `getNullable` that has the current behavior and `get` that throws an exception if there is no registered renderer?

2023-02-13 15:21 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/RendererAccess.java
> +	 * <p>Use {@link Renderer#register(Renderer)} instead.
```suggestion
	 * @deprecated Use {@link Renderer#register(Renderer)} instead.
```

2023-02-13 15:21 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/RendererAccess.java
> +	 * <p>Use {@link Renderer#get()} instead.
```suggestion
	 * @deprecated Use {@link Renderer#get()} instead.
```

2023-02-13 15:21 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/RendererAccess.java
> +	 * <p>Use {@link Renderer#isPresent()} instead.
```suggestion
	 * @deprecated Use {@link Renderer#isPresent()} instead.
```

2023-02-13 23:48 UTC, Technici4n approved these changes

2023-02-14 08:56 UTC, modmuss50 approved these changes

2023-02-14 08:59 UTC, modmuss50 commented
Note to future self: Backport to 1.18.2 and 1.19.2

2023-02-16 12:18 UTC, Player3324 approved these changes

2023-02-23 10:13 UTC, merged