BlockSetTypeRegistry and WoodTypeRegistry
FabricMC/fabric pull request #2916
Opened 2023-02-17 09:10 UTC by Shnupbups

Adds `BlockSetTypeRegistry` for creating `BlockSetType`s using Identifiers. Also adds `WoodTypeRegistry` to replace `SignTypeRegistry`, matching the new more accurate Yarn name. The old `SignTypeRegistry` remains as deprecated for compatibility.

Also updates Yarn build.

2023-02-17 16:32 UTC, apple502j requested changes

2023-02-17 16:32 UTC, apple502j commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/BlockSetTypeRegistry.java
> +	public static BlockSetType registerBlockSetType(Identifier id) {
This should be renamed; the block set created is specifically for overworld woods.

2023-02-17 16:32 UTC, apple502j commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/BlockSetTypeRegistry.java
> +	 * @return a new {@link BlockSetType}.
I don't think `@return` should end with a dot? (same for others)

2023-02-17 16:32 UTC, apple502j commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/WoodTypeRegistry.java
> + * <br>Hanging sign textures are stored as {@code [namespace]/textures/entity/signs/hanging/[path].png}.
Stored at, not as

2023-02-19 11:07 UTC, Technici4n approved these changes

2023-02-19 11:08 UTC, Technici4n requested changes
Just noticed that the method names are redundant... :smile:

2023-02-19 11:08 UTC, Technici4n commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/BlockSetTypeRegistry.java
> +	public static BlockSetType registerWoodBlockSetType(Identifier id) {
Actually, can't we just call this one `registerWood`

2023-02-19 11:08 UTC, Technici4n commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/BlockSetTypeRegistry.java
> +	public static BlockSetType registerBlockSetType(Identifier id, BlockSoundGroup soundType, SoundEvent doorClose, SoundEvent doorOpen, SoundEvent trapdoorClose, SoundEvent trapdoorOpen, SoundEvent pre
And this one `register`?

2023-02-19 11:08 UTC, Technici4n commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/WoodTypeRegistry.java
> +	public static WoodType registerWoodType(Identifier id, BlockSetType setType) {
Just `register`?

2023-02-19 11:08 UTC, Technici4n commented on fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/type/WoodTypeRegistry.java
> +	public static WoodType registerWoodType(Identifier id, BlockSetType setType, BlockSoundGroup soundType, BlockSoundGroup hangingSignSoundType, SoundEvent fenceGateClose, SoundEvent fenceGateOpen) {
Just `register`?

2023-02-20 16:36 UTC, Technici4n approved these changes

2023-02-20 17:16 UTC, modmuss50 approved these changes

2023-02-22 12:54 UTC, merged