Tatar Translation for Fabric API.
FabricMC/fabric pull request #2921
Opened 2023-02-20 17:19 UTC by Amirhan-Taipovjan-Greatest-I

Hello!
There's all Fabric API's translation files that in Tatar language. Can you add them, please?

2023-02-20 17:21 UTC, Technici4n requested changes
Thank you for the contribution. Please remove the translations for the testmods.

2023-02-20 17:30 UTC, Amirhan-Taipovjan-Greatest-I commented
> Thank you for the contribution. Please remove the translations for the testmods.

Did I delete all translations for the testmods?

2023-02-20 17:43 UTC, Technici4n commented on fabric-game-rule-api-v1/src/testmod/resources/assets/fabric-gamerule-test/lang/tt_ru.json
> +{
This is still a testmod

2023-02-20 18:10 UTC, Amirhan-Taipovjan-Greatest-I commented on fabric-game-rule-api-v1/src/testmod/resources/assets/fabric-gamerule-test/lang/tt_ru.json
> +{
> This is still a testmod

I deleted it too.

2023-02-23 07:01 UTC, Amirhan-Taipovjan-Greatest-I commented
I guess... there's no testmod translations now.

2023-02-25 08:07 UTC, closed without merging