Pass ScreenHandler to ExtendedScreenHandlerFactory
FabricMC/fabric pull request #2964
Opened 2023-03-13 21:33 UTC by Devan-Kerman

Addresses #2963

In order to retain backwards compatibility with the old API, a second interface (WithScreenHandler) was created, that throws if you use the old method to initialize it.

2023-04-27 23:13 UTC, modmuss50 requested changes

2023-04-27 23:13 UTC, modmuss50 commented on fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/impl/screenhandler/Networking.java
> +		if(factory instanceof ExtendedScreenHandlerFactory.WithScreenHandler withHandlerFactory) {
Please fix checkstyle

2023-05-10 08:31 UTC, Technici4n commented
This approach compromises the quality of the API. A workaround is to use a different screen handler factory every time and store the screen handler in it.

2023-05-24 20:52 UTC, modmuss50 commented
I have created a new PR with a much cleaner none breaking fix: https://github.com/FabricMC/fabric/pull/3077 please let me know what you think.

2023-05-30 11:58 UTC, closed without merging