Convention Tags Improvements
FabricMC/fabric pull request #3051
Opened 2023-05-07 14:53 UTC by Technici4n

Various convention tag improvements. I'll push more commits, but I'm already opening the PR to keep things organized and ensure that each commit builds separately.

- Cleanup code:
  - Fix `.gitignore` not properly including the generated file.
  - Use `copy` instead of rebuilding tags entirely when they exist both for blocks and for items.
  - Reorder tags a bit, especially block tags so they match item tags.
- Add item version of the block tags where it made sense.
- Add tags for budding blocks: `c:budding_blocks`, `c:buds`, `c:clusters`.
- Add resource category tags: `c:dusts`, `c:gems`, etc...
- Add `c:wooden_barrels`.

**Since these tags are mostly based on community usage, I would appreciate that casual readers have a look and verify that everything makes sense. If you disagree with anything, don't hesitate to say so.**

2023-05-09 09:17 UTC, modmuss50 approved these changes

2023-05-10 12:43 UTC, oliviathevampire commented
Idk if we already have this, but tags for terracotta, concrete, concrete dust, glazed terracotta and mostly all the colored stuff, would be super nice

2023-05-10 12:47 UTC, Technici4n commented
`#minecraft:terracotta` already exists for example. I am not sure about the others.

2023-05-14 10:13 UTC, apple502j requested changes

2023-05-14 10:13 UTC, apple502j commented on fabric-convention-tags-v1/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/BlockTagGenerator.java
> +				.add(Blocks.CAULDRON)
Needs cauldron variants (though not the tag, as the game does not use it for this purpose)

2023-05-14 14:00 UTC, merged