TAWs for worldgen
FabricMC/fabric pull request #3060
Opened 2023-05-13 12:44 UTC by maityyy

Many worldgen mods use this

2023-05-13 13:09 UTC, modmuss50 requested changes

2023-05-13 13:09 UTC, modmuss50 commented on fabric-transitive-access-wideners-v1/src/main/resources/fabric-transitive-access-wideners-v1.accesswidener
> +accessible method net/minecraft/world/gen/trunk/TrunkPlacerType <init> (Lcom/mojang/serialization/Codec;)V
`RootPlacerType` might be useful as well.

2023-05-13 13:09 UTC, modmuss50 commented on fabric-transitive-access-wideners-v1/build.gradle
> -
No need to remove this line. Im not too bothered either way.

2023-05-14 10:03 UTC, modmuss50 approved these changes

2023-05-14 13:34 UTC, maityyy commented
oops, my bad

2023-05-14 13:56 UTC, merged