Material inspection
FabricMC/fabric pull request #3066
Opened 2023-05-16 22:56 UTC by PepperCode1

- Add `MaterialView` to retrieve material properties from `RenderMaterial` and `MaterialFinder`
- Add `MaterialFinder#copyFrom(MaterialView)` to copy properties from another `MaterialView`
- Finish todo in `QuadView#toBakedQuad`
- Move material impl classes to `material` package

2023-05-17 09:31 UTC, Technici4n requested changes
First batch of comments.

2023-05-17 09:31 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialFinder.java
> +	 * @apiNote The default implementation will be removed in the next breaking release.
Needs documentation explaining what this does. (Similar to `ambientOcclusion` which also uses a `TriState`).

2023-05-17 09:31 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialFinder.java
> +	 * @apiNote The default implementation will be removed in the next breaking release.
Needs documentation too.

2023-05-17 09:31 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialView.java
> + * Getter methods for {@link RenderMaterial} (immutable) and {@link MaterialFinder} (mutable).
This must mention that the properties may not match exactly what was requested depending on the renderer implementation. Something like https://discord.com/channels/507304429255393322/566276937035546624/951272466116915290.

2023-05-17 09:31 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialView.java
> +public interface MaterialView {
We can link the `MaterialFinder` functions as javadoc to explain what the methods do. I think a simple `@see MaterialFinder#relevantMethod` would do.

2023-05-17 09:31 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/model/FabricBakedModel.java
> -import net.minecraft.world.BlockRenderView;
Should not reformat imports in unrelated files.

2023-05-17 09:31 UTC, Technici4n commented on fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/impl/client/indigo/renderer/material/RenderMaterialImpl.java
> +	private final BlendMode blendMode;
This increases the size of materials quite a bit. Is it really needed? It wasn't before...

2023-05-17 09:31 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialFinder.java
> +	default MaterialFinder copyFrom(MaterialView material) {
Remember to also add `copyFrom` in `MutableQuadView` as discussed.

2023-05-17 09:31 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialFinder.java
> +	 * @apiNote The default implementation will be removed in the next breaking release.
It's quite important to mention that this property only works in item contexts, and will be entirely ignored in block contexts.

2023-05-18 19:43 UTC, Technici4n approved these changes
Perfect, thank you!

The following uses of `RenderMaterialImpl` can be replaced by `RenderMaterial` if you would like to, I leave that up to you:
- return value of `EncodingFormat#material(int)`
- return value of `QuadViewImpl#material()`
- type of `RenderMaterialImpl#BY_INDEX`
- return value of `RenderMaterial#byIndex`
- return value of `RenderMaterial#setDisableDiffuse`

2023-05-19 13:49 UTC, modmuss50 approved these changes

2023-05-24 15:30 UTC, merged