Add metadata information to POMs
FabricMC/fabric pull request #3074
Opened 2023-05-24 01:39 UTC by romangraef

2023-05-25 07:58 UTC, modmuss50 requested changes
If we are going to do this, I think we should make sure to populate it fully. See my comments and https://github.com/FabricMC/mapping-io/blob/master/build.gradle#L99 for some ideas.

2023-05-25 07:58 UTC, modmuss50 commented on build.gradle
> +		url = "https://github.com/FabricMC/fabric"
A few more things can be added to the scm as seen here: https://github.com/FabricMC/mapping-io/blob/master/build.gradle#L104

2023-05-25 07:58 UTC, modmuss50 commented on build.gradle
> +def addPomMetadataInformation(MavenPom pom) {
Would be nice to also set name and url. description could possibly be driven by the fabric.mod.json file, but thats a little more effort.

2023-05-25 07:58 UTC, modmuss50 commented on build.gradle
> +			name = "Apache 2.0"
```suggestion
			name = "Apache-2.0"
```

According to the [docs](https://maven.apache.org/pom.html#Licenses) Using an [SPDX identifier](https://spdx.org/licenses/) as the license name is recommended.

2023-05-25 07:58 UTC, modmuss50 commented on build.gradle
> +def addPomMetadataInformation(MavenPom pom) {
issueManagement might be another useful one to add.

2023-05-29 11:33 UTC, modmuss50 requested changes
This is looking good, nice work reading it from the FMJ. Im not too keen on using grgit like this as people can and do build it without being in a git repo.

2023-05-29 11:33 UTC, modmuss50 commented on build.gradle
> +import org.kohsuke.github.GHReleaseBuilder
No need to move these imports, I think its generally better to keep the imports close to where they are used.

2023-05-29 11:33 UTC, modmuss50 commented on build.gradle
> +	pom.name = modJson.name
Great idea 👍

2023-05-29 11:33 UTC, modmuss50 commented on build.gradle
> +	pom.url = "https://github.com/FabricMC/fabric/tree/${grgit.head().abbreviatedId}/${project.rootDir.relativePath(project.projectDir)}"
I would just hard code the URL to `https://github.com/FabricMC/fabric`, as this wont work if someone tries to build it outside of a github repo. (Such as when you just download the zip from github)

2023-05-29 11:33 UTC, modmuss50 commented on build.gradle
> +			url = "https://github.com/FabricMC/fabric/blob/${grgit.head().abbreviatedId}/LICENSE"
Again, dont use git here.

2023-05-29 11:33 UTC, modmuss50 commented on build.gradle
> +
Revert these import changes.

2023-05-29 11:46 UTC, romangraef commented
@modmuss50 I now made grgit optional. I can also entirely remove it, if you want that.

2023-05-29 11:47 UTC, modmuss50 commented
> @modmuss50 I now made grgit optional. I can also entirely remove it, if you want that.

I think it would be best, helps enusre that its consitant between runs.

2023-05-29 11:52 UTC, modmuss50 approved these changes

2023-05-30 11:52 UTC, merged