Fix default fluid names for non-placeable fluids, clarify Storage iterator lifecycle with modification
FabricMC/fabric pull request #3141
Opened 2023-06-24 10:11 UTC by Technici4n

Fixes #3114. Fixes #3123.

2023-06-25 11:02 UTC, modmuss50 approved these changes

2023-06-25 22:37 UTC, Juuxel requested changes

2023-06-25 22:37 UTC, Juuxel commented on fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributeHandler.java
> +		if (fluidBlock == Blocks.AIR) {
This check for `fluidVariant.getFluid() != Fluids.EMPTY` to avoid changing vanilla behaviour as the translation key would be different.

2023-06-26 08:00 UTC, Technici4n commented on fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/fluid/FluidVariantAttributeHandler.java
> +		if (fluidBlock == Blocks.AIR) {
Whoops thank you so much, this is embarrassing. 😄

2023-06-26 15:26 UTC, Juuxel approved these changes

2023-07-03 12:11 UTC, merged