Fix injected resources not overriding certain vanilla resources (1.20)
FabricMC/fabric pull request #3164
Opened 2023-07-02 20:07 UTC by NebelNidas

Mods can override vanilla textures just fine by placing files into `resources/assets/minecraft`:
![Default](https://github.com/FabricMC/fabric/assets/48808497/4e0d8447-f290-400e-9040-1271e9fb25ab)

However, the same doesn't work (at least not consistently) for injected resources (via `resources/programmer_art/assets/minecraft` for example):
![Injected Current](https://github.com/FabricMC/fabric/assets/48808497/8bf62091-4b26-40ca-b0a9-5d7f70ff069d)

This PR fixes the inconsistent behavior:
![Injected Fixed](https://github.com/FabricMC/fabric/assets/48808497/3d581686-2e6b-4e56-ac13-f851210fa52d)

2023-07-02 23:56 UTC, Technici4n requested changes
Looks good indeed.

There's a few related problems that should be fixed too:
- `GroupResourcePack#findResources` should iterate first-to-last.
- `GroupResourcePack#appendResources` should iterate last-to-first.
Can you add them to this PR?

2023-07-03 11:43 UTC, NebelNidas commented
Done! I've also removed some redundant code while being at it

2023-07-03 11:57 UTC, modmuss50 commented
The build failure is due to checkstyle 👍

2023-07-03 12:00 UTC, NebelNidas commented
Oops, should be fixed now

2023-07-03 12:03 UTC, modmuss50 commented on fabric-resource-loader-v0/src/testmod/resources/assets/minecraft/textures/block/dirt.png
I dont think we want to override dirt and gravel in the test mod, its a little bit invasive. Maybe a diamond block or something that has to be placed?

2023-07-03 12:07 UTC, NebelNidas commented on fabric-resource-loader-v0/src/testmod/resources/assets/minecraft/textures/block/dirt.png
Dirt seemed like a good candidate because the [built-in resourcepack test overrides it as well](https://github.com/FabricMC/fabric/blob/28c34730642b48d9d4de2f1d4c306204520c1599/fabric-resource-loader-v0/src/testmod/resources/resourcepacks/test/assets/minecraft/textures/block/dirt.png), so overriding dirt in via injected resourcepack simultaneously allows us to check if prioritization between injected packs and built-in packs works.
As for gravel, I just chose a random non-dirt vanilla block, since dirt already had some weird behavior with injected resources (see my second screenshot above).

2023-07-03 12:15 UTC, Technici4n approved these changes
The code changes are good, thanks a lot.

2023-07-03 12:24 UTC, modmuss50 commented on fabric-resource-loader-v0/src/testmod/resources/assets/minecraft/textures/block/dirt.png
I know the test mods do make a few werid changes to the world, but I think this is a little extreme. Id prefer to know that I need to place a block to test this feature. In the future we can possibly look into adding some automated tests for this. it should be trivial to change this PR to override another vanilla block.

2023-07-03 12:53 UTC, modmuss50 approved these changes

2023-07-03 12:54 UTC, merged