Improve Indigo and FRAPI Test Mod
FabricMC/fabric pull request #3208
Opened 2023-07-20 15:40 UTC by PepperCode1

### Improve flat shade

- Use AO mode to make flat shade calculation consistent with shade applied by smooth lighting
- Use face normal to calculate shade if necessary
- Use normal shade even if no custom normals are set

 ### Improve FRAPI test mod

- Add octagonal column to test irregular face lighting
- Improve `PillarBakedModel` to fully support custom block appearance 
- Use obsidian sprite instead of missing sprite for frame mesh
- Simplify and organize registration
- Inline `simple` package

2023-07-31 14:05 UTC, Technici4n requested changes

2023-07-31 14:05 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/mixin/renderer/client/OverlayVertexConsumerMixin.java
> +	private Direction redirectGetFacing(float x, float y, float z) {
Would be nice to add a comment explaining the issue.

2023-08-02 23:18 UTC, Technici4n approved these changes

2023-08-09 19:34 UTC, modmuss50 approved these changes

2023-08-13 15:01 UTC, merged