Fix data generation for custom dynamic registry
FabricMC/fabric pull request #3216
Opened 2023-07-23 08:15 UTC by apple502j

Fixes #3215

This also adds a test for the dynamic registry provider.

2023-07-23 08:19 UTC, Technici4n commented
Should this only be done for registries registered via the API?

2023-07-23 13:38 UTC, apple502j commented
@Technici4n Perhaps. Another solution is to make a new method (with the check you mentioned in place), which providers can override.

2023-07-24 11:47 UTC, modmuss50 requested changes
The code changes are fine, however I think we should really demonstate the correct pattern for the testmod.

2023-07-24 11:47 UTC, modmuss50 commented on fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestContent.java
> +	public static final TestDatagenObject TEST_DYNAMIC_REGISTRY_ITEM = new TestDatagenObject(":tiny_potato:");
I dont think this follows the correct pattern (Fabric API should set a good example), this should only be created in the datagenerator's buildRegistry.

2023-07-24 11:47 UTC, modmuss50 commented on fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
> +				(registerable) -> { }
I would create a full method for this and register the test entry to this `Registerable` see TestBiomes.bootstrap()

2023-07-24 11:47 UTC, modmuss50 commented on fabric-data-generation-api-v1/src/testmod/java/net/fabricmc/fabric/test/datagen/DataGeneratorTestEntrypoint.java
> +			entries.add(TEST_DYNAMIC_REGISTRY_ITEM_KEY, TEST_DYNAMIC_REGISTRY_ITEM);
`TEST_DYNAMIC_REGISTRY_ITEM` should be retrived via the WrapperLookup and not have a constant.

2023-07-25 12:44 UTC, modmuss50 approved these changes

2023-07-25 12:52 UTC, modmuss50 commented
> Should this only be done for registries registered via the API?

Yeah, I think this would be wise, and should match what is done in https://github.com/FabricMC/fabric/pull/3219

I will merge 3219 first, and then update this to use the stuff added in this PR.

2023-07-25 13:21 UTC, merged