Attempt #6 at a Fabric Data Fixer API
FabricMC/fabric pull request #3649
Opened 2024-03-14 23:40 UTC by Treetrain1

This is a copy of #3644 with changes to attempt to merge datafixers into one patch to hopefully remove isolation issues across datafixers.

This currently is only confirmed to work when only a single datafixer is registered. More work needs to be done to properly combine datafixers.

Todo:
- [ ] Fix rewrite rule merging
- [ ] Add tests for the schema registry and rewrite rule merging

2024-03-27 16:36 UTC, Treetrain1 commented
The only concern I have left is that since the schemas are in a single parent line, any mod could cancel the registration of block entities and entities within the schemas by not calling `super.registerBlockEntities` in a schema.
Correct me if I am wrong, but wouldn’t this break all of the parent data fixers?

2024-03-27 16:44 UTC, Treetrain1 commented
Also, I’m wondering what the best way to get molders to register their block entities and entities to the schema would be. Perhaps an integration into the Fabric docs website wherever it talks about block entities and entities and an announcement somewhere.
In any case, if this is merged, I think modders should get notified in some way about this.

2024-03-27 16:49 UTC, Treetrain1 commented
Question.
The vanilla block entity and entity builders have a `String` id parameter that is used to find an instance of the id in the schemas.
Fabric basically ignores this with its builders and builds anyway, so I’m wondering if this should be implemented alongside this PR.

This is already included in this PR (though likely controversial since it logs an error), but I’m wondering what any of your thoughts are on this.

2024-04-02 18:48 UTC, LlamaLad7 requested changes

2024-04-02 18:48 UTC, LlamaLad7 commented on fabric-data-fixer-api-v1/src/testmod/java/net/fabricmc/fabric/test/datafixer/v1/mixin/RegistryLoaderMixin.java
> +					shift = At.Shift.BEFORE
The shift is presumably unnecessary.

2024-04-02 18:48 UTC, LlamaLad7 commented on fabric-data-fixer-api-v1/src/testmod/java/net/fabricmc/fabric/test/datafixer/v1/mixin/RegistryLoaderMixin.java
> +			locals = LocalCapture.CAPTURE_FAILHARD
Never use `LocalCapture`, at all. MixinExtras' `@Local` is preferable but this should be a `@ModifyReceiver` anyway and it does not need locals.

2024-07-12 21:48 UTC, lukebemish commented
I believe this still has the exact same schema/fixer ordering transitiveness issues it did way back last time I took a poke at it? (Namely, issues with mutual transitiveness between different mods as fixers to fix transitive entries are only applied the one time) At any rate, no changes have been made that would resolve those issues.

2024-07-12 21:55 UTC, lukebemish commented
To elaborate: mod A and B add an item and a BE each, which they want to fix. Mod A adds both to a schema and adds a fixer for each afterwards. Mod B does the same. DFU _only_ runs fixers during the specific update step when that fixer exists -- so if mod A's stuff is before mod B's, then a mod A item in a mod B BE will not be properly fixed.

2025-04-07 06:10 UTC, closed without merging