Fix new tags not being plural
FabricMC/fabric pull request #3848
Opened 2024-06-12 21:58 UTC by TelepathicGrunt

This is entirely my fault. I should've caught the typoes. Gave them the same treatment as the tool tags of deprecating the typoed stuff

Fixes https://github.com/FabricMC/fabric/pull/3807

Matches https://github.com/neoforged/NeoForge/pull/1030

2024-06-12 22:12 UTC, haykam821 requested changes

2024-06-12 22:12 UTC, haykam821 commented on fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
>  	 * Block tag equivalent is {@link BlockTags#CONCRETE_POWDER}.
```suggestion
	 * Block tag equivalent is {@link BlockTags#CONCRETE_POWDERS}.
```

2024-06-12 22:12 UTC, haykam821 commented on fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
> +		translationBuilder.add(ConventionalItemTags.GLAZED_TERRACOTTAS, "Glaze Terracottas");
```suggestion
		translationBuilder.add(ConventionalItemTags.GLAZED_TERRACOTTAS, "Glazed Terracottas");
```

2024-06-12 22:12 UTC, haykam821 commented on fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
> +		translationBuilder.add(ConventionalItemTags.GLAZED_TERRACOTTA, "Glaze Terracotta");
```suggestion
		translationBuilder.add(ConventionalItemTags.GLAZED_TERRACOTTA, "Glazed Terracotta");
```

2024-06-12 22:12 UTC, haykam821 commented on fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
> +		translationBuilder.add(ConventionalBlockTags.GLAZED_TERRACOTTAS, "Glaze Terracottas");
```suggestion
		translationBuilder.add(ConventionalBlockTags.GLAZED_TERRACOTTAS, "Glazed Terracottas");
```

2024-06-12 22:12 UTC, haykam821 commented on fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
> +		translationBuilder.add(ConventionalBlockTags.GLAZED_TERRACOTTA, "Glaze Terracotta");
```suggestion
		translationBuilder.add(ConventionalBlockTags.GLAZED_TERRACOTTA, "Glazed Terracotta");
```

2024-06-13 08:13 UTC, modmuss50 commented on fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
> +		translationBuilder.add(ConventionalBlockTags.GLAZED_TERRACOTTA, "Glaze Terracotta");
Resources need re-generating after applying these changes.

2024-06-13 11:17 UTC, TelepathicGrunt commented on fabric-convention-tags-v2/src/datagen/java/net/fabricmc/fabric/impl/tag/convention/datagen/generators/EnglishTagLangGenerator.java
> +		translationBuilder.add(ConventionalBlockTags.GLAZED_TERRACOTTA, "Glaze Terracotta");
done in b5893fff445073752c88dc4cf69956acf19840a6

2024-06-16 17:18 UTC, TelepathicGrunt commented
@modmuss50 any concerns or is this good for approval?

2024-06-16 17:19 UTC, modmuss50 commented
> @modmuss50 any concerns or is this good for approval?

Sorry, been a bit busy (IRL things, and porting my mod to 1.21 :D ). Ill try and take ASAP.

2024-06-17 08:17 UTC, modmuss50 approved these changes

2024-06-17 17:10 UTC, merged