Add `ShadeMode` to FRAPI
FabricMC/fabric pull request #3937
Opened 2024-07-13 04:50 UTC by PepperCode1

2024-07-21 17:19 UTC, Technici4n requested changes
I did not run the code, but I had a thorough look at every change. Looks very good.

2024-07-21 17:19 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialFinder.java
> +	 * <p>The default value is {@code false}.
That's not very clear. The default value is `{@code false}`, which means that the vertex colors _will be modified_. What about this?

```suggestion
	 * Controls whether vertex colors should be modified for quad coloring.
	 *
	 * <p>The default value is {@code false}, meaning that vertices will be colored according to the color index.
```

2024-07-21 17:19 UTC, Technici4n commented on fabric-renderer-api-v1/src/client/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialFinder.java
> +	 * <p>The default value is {@code false}.
```suggestion
	 * <p>The default value is {@code false}, which enables diffuse shading.
```

2024-07-25 21:36 UTC, Technici4n approved these changes

2024-07-27 14:51 UTC, modmuss50 approved these changes

2024-08-04 12:52 UTC, merged