Add `c:slimeballs` tag, add more melee weapons to melee tag, and Sparse Jungle to Sparse tag
FabricMC/fabric pull request #3957
Opened 2024-07-19 11:39 UTC by TelepathicGrunt

- Adds Sparse Jungle to `c:is_sparse_vegetation/overworld` biome tag as it was missing from before. The biome belongs there. It got sparse in the name!

- Added Trident, Pickaxes, Shovels, and Hoes to the `c:tools/melee_weapon` item tag. Reason is to make it more clear of what is a melee weapon. The definition now is any item that has a GENERIC_ATTACK_DAMAGE attribute is considered melee as the damage increase is what the main thing that separates melee weapons from smacking a mob with a stick. Clarified the javadocs in these areas for what is in these tags.

- Added `c:slimeballs` tag to match NeoForge and because someone requested it on Fabric. Showing there is use case for this tag likely due to mods that do Slimes that drop ore-based slimeballs or something.

Neo PR: https://github.com/neoforged/NeoForge/pull/1348

closes [#3946](https://github.com/FabricMC/fabric/issues/3946)
closes [#3949](https://github.com/FabricMC/fabric/issues/3949)

2024-07-23 20:22 UTC, Chocohead requested changes
Would be good to link Minecraft references so any changes in the future won't get missed in the Javadocs

2024-07-23 20:22 UTC, Chocohead commented on fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
> +	 * Tools are considered melee if they contain a GENERIC_ATTACK_DAMAGE attribute.
```suggestion
	 * Tools are considered melee if they contain a {@link net.minecraft.entity.attribute.EntityAttributes#GENERIC_ATTACK_DAMAGE} attribute.
```

2024-07-23 20:22 UTC, Chocohead commented on fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java
> +	 * (Note: Could include durability-based modded bonemeal-like items. Check for durability DataComponentType to handle them properly)
```suggestion
	 * (Note: Could include durability-based modded bonemeal-like items. Check for durability {@link net.minecraft.component.ComponentType} to handle them properly)
```

2024-07-24 12:29 UTC, Crendgrim commented
Hm, as a mod dev I'm not a big fan of the change to `c:tools/melee_weapons`. It was nice to have a common tag that basically meant "this is a melee weapon". I don't see a good way to filter things out again because there's no common tags for shovels/hoes/paxels/whatever mods add that do damage but aren't actually melee weapons. Also, it is confusing that `c:tools` now includes `c:spear_tools`, but `c:tools/melee_weapons` hardcodes the trident. If a mod adds a trident, it automatically appears in one collective tag but not the other.

2024-07-24 12:35 UTC, TelepathicGrunt commented
@Crendgrim You can use the diff ingredients to filter out shovels, hoes, and pickaxes. Maybe even axes too if that's not something you want. So adding more entries is fine since we can filter them later in datapacks using modloader's diff ingredients if desired. It’s the same logic we encourage with the dyed tags. See the javadoc here for more info: https://github.com/FabricMC/fabric/blob/f9000df732297d583eb96c98ec0341da06c1d1c6/fabric-convention-tags-v2/src/main/java/net/fabricmc/fabric/api/tag/convention/v2/ConventionalItemTags.java#L245

the reason I did not nest tags into the melee tag is because someone can make a sword that does not have the attack damage attribute and instead, shoots fireball projectiles. That sword would be in sword tag because it is a sword. But it is not a melee weapon. Same goes for axes, spears, etc. it is better to individually define each item in the melee tag so modders can add their weapons only if it is truly a melee weapon and not some case where it doing unique behavior than the rest of the similar tools do

2024-07-24 12:40 UTC, TelepathicGrunt commented
@Crendgrim to clarify a bit more on first point, there are shovel and hoe tags. They are under the Mc namespace https://github.com/misode/mcmeta/blob/data-json/data/minecraft/tags/item/shovels.json

But again, if they define an attack damage attribute, they are defined to deal more damage than hand or other normal items. That makes them well, a weapon. More efficient at killing than empty hand. Now you may have specific use case for *specific* kinds of weapons and that’s where ingredient difference/intersection comes into play as that is its entire purpose to allow you to pick exactly what you need from a tag

2024-07-31 11:42 UTC, modmuss50 approved these changes

2024-08-04 12:52 UTC, merged