Add methods for setting render layer of multiple objects with one call
FabricMC/fabric pull request #444
Opened 2019-11-26 17:55 UTC by Juuxel

Closes #438.

Adds three utility methods to `BlockRenderLayerMap`: `putBlocks`, `putItems` and `putFluids`, which set the render layer of multiple entries with a single call.

2019-11-26 18:25 UTC, grondag approved these changes
Nice little improvement.

2019-11-26 19:19 UTC, liach commented
Iterable versions please (in case ppl put blocks in a map, e.g. wood type to custom woodware block map's values)

2019-11-26 19:24 UTC, grondag commented
Would object to iterable but having array-based is nice, too. 

For something like this I wonder if default methods on the API interface  are appropriate. Makes the code a less extensive and doesn’t expose anything interesting about the implementation.

2019-11-27 10:07 UTC, Player3324 approved these changes

2019-11-27 10:10 UTC, liach approved these changes

2019-11-28 17:55 UTC, modmuss50 requested changes
Looks good, please bump the main project and module version.

2019-11-28 18:31 UTC, modmuss50 approved these changes

2019-11-28 18:32 UTC, modmuss50 commented
I will merge at the same time as the pre 3 update this evening.

Thanks.

2019-11-28 18:35 UTC, coderbot16 approved these changes

2019-11-28 19:46 UTC, modmuss50 commented
Merged via IDE, not sure why this hasnt closed. Thanks.

2019-11-28 19:46 UTC, closed without merging