DataFixers, third times a charm with an incremental approach
FabricMC/fabric pull request #522
Opened 2020-03-11 02:39 UTC by i509VCB

My last 2 DataFixer PRs had a major flaw: They were far too big. So this time I've decided to split up the process into more digestible bits. These pieces of the puzzle are the simplest to understand, so we start here.

This PR only includes:
A way for mods to register a datafixer for.
3 Simple fixes: Biome, Block and Item renames.

More advanced features will come in future PRs.

This supersedes #371 and #440

2020-03-11 02:46 UTC, liach reviewed
Looks fairly good on first sight

2020-03-11 02:46 UTC, liach commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/api/datafixer/v1/DataFixerHelper.java
> +	 * @param runtimeDataVersion the current dataversion of the mod being ran.
how about `currentVersion`

2020-03-11 02:46 UTC, liach commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/api/datafixer/v1/DataFixerHelper.java
> +public interface DataFixerHelper {
like `FabricDataFixes`? don't think this name is super clear

2020-03-19 14:14 UTC, Juuxel commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/api/datafixer/v1/FabricSchemas.java
> +	 * Normalize Identifier Schema.
This comment seems a bit pointless.

2020-03-19 14:20 UTC, Juuxel requested changes
Some fixes for the cursed capitalization of "mod ID".

2020-03-19 14:20 UTC, Juuxel commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/api/datafixer/v1/FabricDataFixes.java
> +	DataFixer getDataFixer(String modid);
```suggestion
	DataFixer getDataFixer(String modId);
```

2020-03-19 14:20 UTC, Juuxel commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/api/datafixer/v1/FabricDataFixes.java
> +	 * @param modid The modid of the mod registering this DataFixer
```suggestion
	 * @param modId The ID of the mod registering this DataFixer
```

2020-03-19 14:20 UTC, Juuxel commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/api/datafixer/v1/FabricDataFixes.java
> +	DataFixer registerFixer(String modid, int currentVersion, DataFixer dataFixer);
```suggestion
	DataFixer registerFixer(String modId, int currentVersion, DataFixer dataFixer);
```

2020-03-19 14:20 UTC, Juuxel commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/api/datafixer/v1/FabricDataFixes.java
> +	 * @param modid The mod which the DataFixer was registered under.
```suggestion
	 * @param modId The mod which the DataFixer was registered under.
```

2020-03-19 14:20 UTC, Juuxel commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/api/datafixer/v1/FabricDataFixes.java
> +	 * @param modid The id of the mod to check.
```suggestion
	 * @param modId The id of the mod to check.
```

2020-03-19 14:20 UTC, Juuxel commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/api/datafixer/v1/FabricDataFixes.java
> +	int getModDataVersion(CompoundTag compoundTag, String modid);
```suggestion
	int getModDataVersion(CompoundTag compoundTag, String modId);
```

2020-04-05 01:52 UTC, liach commented on fabric-datafixer-v1/src/main/java/net/fabricmc/fabric/impl/datafixer/FabricDataFixesImpl.java
> +	public DataFixer registerFixer(String modid, int currentVersion, DataFixer datafixer) {
Still need to replace `modid` with `modId` in this file

2020-05-03 09:59 UTC, Juuxel approved these changes

2020-05-03 16:47 UTC, Ueaj-Kerman approved these changes

2020-05-03 17:54 UTC, liach approved these changes
Remember to update to `fabric-datafixer-api-v1`

2020-08-14 05:35 UTC, i509VCB commented
I need to find time to work on this soon lol

2020-10-03 20:42 UTC, i509VCB commented
Going to close this PR and reopen in the future. There are more important pull requests that need to be attended to

2020-10-03 20:42 UTC, closed without merging