Update build.gradle for testing
FabricMC/fabric pull request #550
Opened 2020-04-02 19:03 UTC by liach

Signed-off-by: liach <liach@users.noreply.github.com>

For a preview, should work in theory

2020-04-02 20:16 UTC, i509VCB requested changes

2020-04-02 20:16 UTC, i509VCB commented on fabric-api-base/src/main/java/net/fabricmc/fabric/api/util/NbtType.java
> + * @see CompoundTag#contains(String, int)
Based on the title of the PR, this has no relation to the `build.gradle`

However the name of the branch you used ` liachmodded:fix/javadoc-build` makes me think this is to fix javadoc.

So I would say either change the name of the PR to mention the whole picture or scope the javadoc fixes to another PR

2020-04-02 20:16 UTC, i509VCB commented on fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/EntityPlacer.java
> +	 * Utilized by {@link FabricDimensions#teleport(Entity, net.minecraft.world.dimension.DimensionType, EntityPlacer)} to specify placement logic when needed.
We don't need to fully qualify this do we?

2020-04-02 20:16 UTC, i509VCB commented on fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandler.java
> +	 * <p>Note: As of right now, our hook cannot handle setting a custom alpha
Why not `@apiNote`

2020-04-02 20:16 UTC, i509VCB commented on fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/model/FabricBakedModel.java
> +	 * <p>Note: with {@link BakedModel#getQuads(BlockState, net.minecraft.util.math.Direction, Random)}, the random
Why not `@apiNote`

2020-04-02 20:16 UTC, i509VCB commented on fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/mesh/MutableQuadView.java
> +	 * <p>Note: This value is not persisted independently when the quad is encoded.
`@apiNote`

2020-04-02 20:44 UTC, liach commented on fabric-api-base/src/main/java/net/fabricmc/fabric/api/util/NbtType.java
> + * @see CompoundTag#contains(String, int)
Oh, this pr fixes javadoc jar generation and javadoc building

2020-04-02 20:45 UTC, liach commented on fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1/EntityPlacer.java
> +	 * Utilized by {@link FabricDimensions#teleport(Entity, net.minecraft.world.dimension.DimensionType, EntityPlacer)} to specify placement logic when needed.
because importing it would cause a checkstyle error

2020-04-02 20:45 UTC, liach commented on fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandler.java
> +	 * <p>Note: As of right now, our hook cannot handle setting a custom alpha
Just use this for now, this works well and doclint doesn't know `@note`

2020-04-02 20:45 UTC, liach commented on fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/model/FabricBakedModel.java
> +	 * <p>Note: with {@link BakedModel#getQuads(BlockState, net.minecraft.util.math.Direction, Random)}, the random
No

2020-04-02 20:46 UTC, liach commented on fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/mesh/MutableQuadView.java
> +	 * <p>Note: This value is not persisted independently when the quad is encoded.
No, I just make it pass generation, I am not a javadoc pro lol

2020-04-03 19:45 UTC, modmuss50 approved these changes

2020-04-03 19:55 UTC, modmuss50 commented
I would love to this this in quite swiftly, as ive been battling this for a while.

As its none API changing, I will allow a little more time and then pull it in.

All the module that you have touched should have their version bumped please.

2020-04-03 20:02 UTC, i509VCB approved these changes
So I gave it another look, I don't understand most of the gradle wizardry. Of course the fixes for javadoc are a good thing since you've explained that most of them are needed for javadoc to build.

2020-04-04 01:03 UTC, liach commented
The fixed javadoc (built with jdk 14) is available at https://github.com/liachmodded/fabric/tree/4c111e0edd9114a08215d8cad4bd2341c27e4464
A preview is available at https://liachmodded.github.io/fabric/

2020-04-04 13:15 UTC, Player3324 approved these changes

2020-04-05 14:07 UTC, merged