Base+Branch+Build versioning
FabricMC/fabric pull request #588
Opened 2020-04-22 03:26 UTC by halotroop2288

Because I want "0.5.1+1.15+build.+" to work.

This is a change I would obviously like to see on every branch, but I can only make one PR at once, and probably only should do one.

Commence discussion.

2020-04-22 03:52 UTC, sfPlayer1 commented
Not sure why? They are both part of the "informative-only" suffix and having the branch last makes it stand out more. AFAIK `+` is not allowed in the semver build identifier.

2020-04-22 03:59 UTC, halotroop2288 commented
`+` Tells Gradle to get the highest available version when updating dependencies.
When the branch is on the end it gets "-1.16" instead of the one I want, "-1.15."
`0.5.1+1.15+build.+` would get the latest version for 1.15, but `0.5.1+build.+` gets the latest version period (currently 1.16).

2020-04-22 04:21 UTC, Prospector commented
There's nothing particularly wrong with this suggestion, just know that you really should *never* use `+` in gradle, for the same reason Loom should stop using `-SNAPSHOT` versions. Every time you run the gradle script, it should do the exact same thing, given all the maven repos being online (nothing you can do about this). You should never have to worry about unexpected breakages because someone pushed a bad build.

2020-04-22 04:26 UTC, halotroop2288 commented
I agree with that reasoning, but I use `+` anyway, to keep my dependencies constantly up-to-date.
I know how to get issues like that resolved, and I would really prefer to have the option.

2020-04-22 04:44 UTC, liach commented
We need a label for non-backward-compatible breaking changes like this

2020-04-22 04:46 UTC, liach commented
Hmm, looking at loader's semantic version code, I guess with this the build can be correctly parsed for api https://github.com/FabricMC/fabric-loader/blob/master/src/main/java/net/fabricmc/loader/util/version/SemanticVersionImpl.java

2020-04-23 12:59 UTC, modmuss50 requested changes
No, I dont think this makes any diffrence at all, everything after the + should be ignored. 

Having 2 `+`s in the meta also doesnt seem to be in spec.

2020-05-01 23:36 UTC, modmuss50 commented
Closing this as its sloves nothing, and is against spec.

2020-05-01 23:36 UTC, closed without merging